<template><div><h2 id="一、注册dockerhub" tabindex="-1"><a class="header-anchor" href="#一、注册dockerhub"><span>一、注册dockerhub</span></a></h2>
<p>我们先去官网注册dockerhub的账号和密码，官网在下方↓<br>
<a href="https://hub.docker.com/" target="_blank" rel="noopener noreferrer">https://hub.docker.com/</a><br>
登录到这个界面。<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161449105.png" alt="" loading="lazy"></p>
<h2 id="二、安装docker" tabindex="-1"><a class="header-anchor" href="#二、安装docker"><span>二、安装docker</span></a></h2>
<p>详细的安装步骤我们可以采纳以下这个文档<br>
<a href="https://blog.csdn.net/liu_chen_yang/article/details/123842609" target="_blank" rel="noopener noreferrer">linux（centos）中部署docker（步骤超全，含带一些发展史和一些概念）</a></p>
<h2 id="三、编写一个dockerfile打成镜像或者直接pull一个镜像" tabindex="-1"><a class="header-anchor" href="#三、编写一个dockerfile打成镜像或者直接pull一个镜像"><span>三、编写一个dockerfile打成镜像或者直接pull一个镜像</span></a></h2>
<h3 id="_1、编写dockerfile" tabindex="-1"><a class="header-anchor" href="#_1、编写dockerfile"><span>1、编写dockerfile</span></a></h3>
<p>编写一个dockerfile的话，我们可以写一个非常简单的dockerfile；</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Dockerfile</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">FROM</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> centos</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>（1）build一个镜像</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> build</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -f</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Dockerfile</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -t</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mycentos:v1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161449977.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>（2）docker images查看<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161449939.png" alt="" loading="lazy"><br>
这里一个镜像就打好了；</p>
<h3 id="_2、直接pull一个镜像" tabindex="-1"><a class="header-anchor" href="#_2、直接pull一个镜像"><span>2、直接pull一个镜像</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> busybox</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>（1）docker images查看<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161449807.png" alt="" loading="lazy"><br>
这里一个镜像就拉好了；</p>
<h2 id="四、修改镜像标签" tabindex="-1"><a class="header-anchor" href="#四、修改镜像标签"><span>四、修改镜像标签</span></a></h2>
<p><strong><font color=teal>格式：</font></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tag</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 镜像名:版本</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dockerhub用户名/镜像名:版本</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong><font color=teal>实例：</font></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-dark:#7F848E;--shiki-light-font-style:italic;--shiki-dark-font-style:italic">#dockerfile打出来的镜像</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tag</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mycentos:v1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/mycenos:v1</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-dark:#7F848E;--shiki-light-font-style:italic;--shiki-dark-font-style:italic">#pull直接拉取的镜像</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tag</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> busybox:latest</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/busybox:v1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>改完之后就是一下这种：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">root@pzg:[root]docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> images</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">REPOSITORY</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                           TAG</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                         IMAGE</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            CREATED</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             SIZE</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">busybox</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                              latest</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      beae173ccac6</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">        4</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> months</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ago</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        1.24MB</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">liuchenyang/busybox</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                  v1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                          beae173ccac6</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">        4</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> months</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ago</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        1.24MB</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">mycentos</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                             v1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                          5d0da3dc9764</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">        7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> months</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ago</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        231MB</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">liuchenyang/mycenos</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                  v1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                          5d0da3dc9764</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">        7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> months</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ago</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        231MB</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="五、使用命令登录dockerhub" tabindex="-1"><a class="header-anchor" href="#五、使用命令登录dockerhub"><span>五、使用命令登录dockerhub</span></a></h2>
<blockquote>
<p>  我们在这里登录的时候可以docker login -u 用户名指定，也可以直接docker login然后输入用户名和密码；<br>
  还有就是如果已经又用户登录这可以退出登<font color=red>docker logout</font>退出登录。</p>
</blockquote>
<h3 id="_1、-u-指定用户登录" tabindex="-1"><a class="header-anchor" href="#_1、-u-指定用户登录"><span>1、-u 指定用户登录</span></a></h3>
<p>指定用户登录，直接输入密码即可；</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> login</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -u</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450730.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="_2、直接docker-login登录" tabindex="-1"><a class="header-anchor" href="#_2、直接docker-login登录"><span>2、直接docker login登录</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@bogon]# docker login</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Login</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> your</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> images</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Hub.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> If</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> you</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> don't have a Docker ID, head over to https://hub.docker.com to create one.</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Username: liuchenyang</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Password: </span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">WARNING! Your password will be stored unencrypted in /root/.docker/config.json.</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Configure a credential helper to remove this warning. See</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">https://docs.docker.com/engine/reference/commandline/login/#credentials-store</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Login Succeeded</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这样就登录成功了，我就就开始打包镜像，推送镜像。</p>
<h2 id="六、推送镜像到dockerhub" tabindex="-1"><a class="header-anchor" href="#六、推送镜像到dockerhub"><span>六、推送镜像到dockerhub</span></a></h2>
<p><strong><font color=teal>格式：</font></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 修改的镜像名:版本</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong><font color=teal>实例：</font></strong></p>
<p>dockerfile打出来的镜像：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">root@hostname#</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/mycenos:v1</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> refers</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> repository</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [docker.io/liuchenyang/mycenos]</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">74ddd0ec08fa:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Mounted</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> library/centos</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">v1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> digest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> size:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 529</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>docker pull拉取出来的镜像：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">root@hostname#</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/busybox:v1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> refers</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> repository</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [docker.io/liuchenyang/busybox]</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">01fd6df81c8e:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Mounted</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> library/busybox</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">v1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> digest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sha256:62ffc2ed7554e4c6d360bce40bbcf196573dd27c4ce080641a2c59867e732dee</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> size:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 527</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最后显示的有<font color=red>大小多少</font>则是上传成功，然而显示的<font color=red>denied: requested access to the resource is denied</font>则是报错，可以看第八条。</p>
<h2 id="七、查看dockerhub" tabindex="-1"><a class="header-anchor" href="#七、查看dockerhub"><span>七、查看dockerhub</span></a></h2>
<p>这时候我们登录dockerhub官网去查看：<a href="https://hub.docker.com/" target="_blank" rel="noopener noreferrer">dockerhub官网</a><br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450911.png" alt="" loading="lazy"><br>
然后可以看到这时候已经上传到dockerhub中；之后下载镜像也可以直接登录dockerhub账号，然后pull镜像了。</p>
<h2 id="八、denied-requested-access-to-the-resource-is-denied报错详解" tabindex="-1"><a class="header-anchor" href="#八、denied-requested-access-to-the-resource-is-denied报错详解"><span>八、denied: requested access to the resource is denied报错详解</span></a></h2>
<p>如遇到此类报错，可以查看：<a href="https://blog.csdn.net/liu_chen_yang/article/details/124665726?spm=1001.2014.3001.5502" target="_blank" rel="noopener noreferrer">Docker——denied: requested access to the resource is denied问题以及解决方法</a><br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450008.png" alt="" loading="lazy"></p>
<h2 id="九、拉取镜像" tabindex="-1"><a class="header-anchor" href="#九、拉取镜像"><span>九、拉取镜像</span></a></h2>
<p><strong><font color=teal>格式：</font></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dockerhub的镜像名</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong><font color=teal>实例：</font></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">root@locahost#</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/mycenos:v1</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">v1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pulling</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/mycenos</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Digest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Status:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloaded</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> newer</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> image</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> liuchenyang/mycenos:v1</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker.io/liuchenyang/mycenos:v1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450250.png" alt="" loading="lazy"><br>
拉取成功，后续需要修改镜像名可以通过“<font color=red>docker tag 原镜像名 要修改的镜像名</font>” 来修改。<br>
也可以从dockerhub中查看拉取镜像的命令；<br>
点击你想要拉取的镜像；<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450389.png" alt="" loading="lazy"><br>
然后选择tag，就可以看到有一个拉取镜像的命令了；<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450790.png" alt="" loading="lazy"></p>
<h2 id="十、删除dockerhub镜像" tabindex="-1"><a class="header-anchor" href="#十、删除dockerhub镜像"><span>十、删除dockerhub镜像</span></a></h2>
<p>还是先选择要删除的镜像；<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450218.png" alt="" loading="lazy"><br>
然后点击settings，往下面翻就可以看到删除镜像了；<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450793.png" alt="" loading="lazy"><br>
然后会让你再次输入要删除的镜像，就和提示你确认是否删除是一样的，怕你误删；输入完镜像名之后再次点击delete就可以删除了；<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450686.png" alt="" loading="lazy"><br>
然后就可以看到只剩一个镜像了，这时就删除成功了。<br>
<img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161450001.png" alt="" loading="lazy"></p>
<h1 id="总结" tabindex="-1"><a class="header-anchor" href="#总结"><span>总结</span></a></h1>
<p><strong>相关文章：</strong></p>
<blockquote>
<p>①、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124665726?spm=1001.2014.3001.5502" target="_blank" rel="noopener noreferrer">Docker——denied: requested access to the resource is denied问题以及解决方法</a><br>
②、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124705622" target="_blank" rel="noopener noreferrer">Docker搭建harbor私有镜像仓库（命令行模式）</a><br>
③、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124623482" target="_blank" rel="noopener noreferrer">Linux中基于Docker搭建harbor私有镜像仓库（超级详细）</a>🔥🔥</p>
</blockquote>
</div></template>


