export const data = JSON.parse("{\"key\":\"v-6b2668f9\",\"path\":\"/cloud/Zabbix/zabbix%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%91%E6%8E%A7%E9%A1%B9_%E5%91%8A%E8%AD%A6%EF%BC%88%E9%82%AE%E4%BB%B6%EF%BC%89.html\",\"title\":\"🏆前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] &emsp;&emsp;有的时候zabbix提供的监控项目，不能满足我们生产环境下的监控需求，此时我们就要按照zabbix的规范自定义监控项目，来达到监控的目的。 🥈定义监控项介绍 监控项就是监控项目，监控指标，具体的监控内容。 在添加主机时我们会选择关联模板，模板中自带很多监控项，但是很多时候我们需要监控的监控项模板中没有，此时需要自定...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Zabbix/zabbix%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%91%E6%8E%A7%E9%A1%B9_%E5%91%8A%E8%AD%A6%EF%BC%88%E9%82%AE%E4%BB%B6%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🏆前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] &emsp;&emsp;有的时候zabbix提供的监控项目，不能满足我们生产环境下的监控需求，此时我们就要按照zabbix的规范自定义监控项目，来达到监控的目的。 🥈定义监控项介绍 监控项就是监控项目，监控指标，具体的监控内容。 在添加主机时我们会选择关联模板，模板中自带很多监控项，但是很多时候我们需要监控的监控项模板中没有，此时需要自定...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🏆前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🥈定义监控项介绍\",\"slug\":\"🥈定义监控项介绍\",\"link\":\"#🥈定义监控项介绍\",\"children\":[]},{\"level\":2,\"title\":\"🥈客户端\",\"slug\":\"🥈客户端\",\"link\":\"#🥈客户端\",\"children\":[{\"level\":3,\"title\":\"🥉取值\",\"slug\":\"🥉取值\",\"link\":\"#🥉取值\",\"children\":[]},{\"level\":3,\"title\":\"🥉配置\",\"slug\":\"🥉配置\",\"link\":\"#🥉配置\",\"children\":[]}]},{\"level\":2,\"title\":\"🥈服务端\",\"slug\":\"🥈服务端\",\"link\":\"#🥈服务端\",\"children\":[{\"level\":3,\"title\":\"🥉测试\",\"slug\":\"🥉测试\",\"link\":\"#🥉测试\",\"children\":[]}]},{\"level\":2,\"title\":\"🥈web页面\",\"slug\":\"🥈web页面\",\"link\":\"#🥈web页面\",\"children\":[{\"level\":3,\"title\":\"🥉添加监控项\",\"slug\":\"🥉添加监控项\",\"link\":\"#🥉添加监控项\",\"children\":[]},{\"level\":3,\"title\":\"🥉添加触发器\",\"slug\":\"🥉添加触发器\",\"link\":\"#🥉添加触发器\",\"children\":[]},{\"level\":3,\"title\":\"🥉添加报警媒介\",\"slug\":\"🥉添加报警媒介\",\"link\":\"#🥉添加报警媒介\",\"children\":[]},{\"level\":3,\"title\":\"🥉设置用户和报警媒介\",\"slug\":\"🥉设置用户和报警媒介\",\"link\":\"#🥉设置用户和报警媒介\",\"children\":[]},{\"level\":3,\"title\":\"🥉添加动作\",\"slug\":\"🥉添加动作\",\"link\":\"#🥉添加动作\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.24,\"words\":2171},\"filePathRelative\":\"cloud/Zabbix/zabbix添加自定义监控项&告警（邮件）.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
