export const data = JSON.parse("{\"key\":\"v-175aeab6\",\"path\":\"/cloud/Zabbix/zabbix%E9%85%8D%E7%BD%AE%E9%92%89%E9%92%89%E5%91%8A%E8%AD%A6%EF%BC%88%E9%99%84%E5%90%AB%E9%92%89%E9%92%89%E5%91%8A%E8%AD%A6%E8%84%9A%E6%9C%AC%20%C2%B7%20%E5%AE%9E%E6%88%98%E4%BA%B2%E6%B5%8B%E6%97%A0%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%EF%BC%89.html\",\"title\":\"钉钉上操作（钉钉告警以关键词方式告警）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Zabbix/zabbix%E9%85%8D%E7%BD%AE%E9%92%89%E9%92%89%E5%91%8A%E8%AD%A6%EF%BC%88%E9%99%84%E5%90%AB%E9%92%89%E9%92%89%E5%91%8A%E8%AD%A6%E8%84%9A%E6%9C%AC%20%C2%B7%20%E5%AE%9E%E6%88%98%E4%BA%B2%E6%B5%8B%E6%97%A0%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"钉钉上操作（钉钉告警以关键词方式告警）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"钉钉上操作（钉钉告警以关键词方式告警）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"创建钉钉群\",\"slug\":\"创建钉钉群\",\"link\":\"#创建钉钉群\",\"children\":[]},{\"level\":2,\"title\":\"添加机器人-->设置关键词\",\"slug\":\"添加机器人-设置关键词\",\"link\":\"#添加机器人-设置关键词\",\"children\":[]},{\"level\":2,\"title\":\"生成webhook（请保管好webhook的值；后面需要用到。）\",\"slug\":\"生成webhook-请保管好webhook的值-后面需要用到。\",\"link\":\"#生成webhook-请保管好webhook的值-后面需要用到。\",\"children\":[]}],\"readingTime\":{\"minutes\":3.9,\"words\":1170},\"filePathRelative\":\"cloud/Zabbix/zabbix配置钉钉告警（附含钉钉告警脚本 · 实战亲测无任何问题）.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
