export const data = JSON.parse("{\"key\":\"v-0e7760dd\",\"path\":\"/middleware/docker/02%20Docker%20%20Docker%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html\",\"title\":\"Docker常用命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Docker常用命令\",\"icon\":\"circle-info\",\"order\":2,\"pageview\":false,\"date\":\"2023-10-09T15:46:30.000Z\",\"comment\":false,\"breadcrumb\":false,\"category\":[\"docker🛥️\"],\"tag\":[\"docker🛥️\"],\"description\":\"1.前言 大家好，我是Leo哥🫣🫣🫣，众所周知，docker 排查问题相较而言是困难的。因此，熟知一些常用命令对我们快速的排查定位问题是非常有帮助的。 好了，话不多说让我们开始吧😎😎😎。 2.常见命令介绍 下面是一些docker常见的命令 **命令** 说明 **文档地址** :------------- :----------------...\"},\"headers\":[{\"level\":2,\"title\":\"1.前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2.常见命令介绍\",\"slug\":\"_2-常见命令介绍\",\"link\":\"#_2-常见命令介绍\",\"children\":[]},{\"level\":2,\"title\":\"3.详细命令演示\",\"slug\":\"_3-详细命令演示\",\"link\":\"#_3-详细命令演示\",\"children\":[{\"level\":3,\"title\":\"3.1 显示docker的系统信息\",\"slug\":\"_3-1-显示docker的系统信息\",\"link\":\"#_3-1-显示docker的系统信息\",\"children\":[]},{\"level\":3,\"title\":\"3.2 拉取镜像\",\"slug\":\"_3-2-拉取镜像\",\"link\":\"#_3-2-拉取镜像\",\"children\":[]},{\"level\":3,\"title\":\"3.3 查看镜像\",\"slug\":\"_3-3-查看镜像\",\"link\":\"#_3-3-查看镜像\",\"children\":[]},{\"level\":3,\"title\":\"3.4 创建容器\",\"slug\":\"_3-4-创建容器\",\"link\":\"#_3-4-创建容器\",\"children\":[]},{\"level\":3,\"title\":\"3.5 查看运行中容器\",\"slug\":\"_3-5-查看运行中容器\",\"link\":\"#_3-5-查看运行中容器\",\"children\":[]},{\"level\":3,\"title\":\"3.6 查看容器详细信息\",\"slug\":\"_3-6-查看容器详细信息\",\"link\":\"#_3-6-查看容器详细信息\",\"children\":[]},{\"level\":3,\"title\":\"3.7 进入容器内部\",\"slug\":\"_3-7-进入容器内部\",\"link\":\"#_3-7-进入容器内部\",\"children\":[]},{\"level\":3,\"title\":\"3.8 删除容器\",\"slug\":\"_3-8-删除容器\",\"link\":\"#_3-8-删除容器\",\"children\":[]}]},{\"level\":2,\"title\":\"4.命令别名\",\"slug\":\"_4-命令别名\",\"link\":\"#_4-命令别名\",\"children\":[]},{\"level\":2,\"title\":\"5.文章参考\",\"slug\":\"_5-文章参考\",\"link\":\"#_5-文章参考\",\"children\":[]},{\"level\":2,\"title\":\"6.总结\",\"slug\":\"_6-总结\",\"link\":\"#_6-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":3.77,\"words\":1132},\"filePathRelative\":\"middleware/docker/docker-common-commod.md\",\"localizedDate\":\"2023年10月9日\",\"copyright\":{\"author\":\"LeoJavaer(toleojavaer.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
