export const data = JSON.parse("{\"key\":\"v-032c5f92\",\"path\":\"/middleware/docker/06%20Docker%20%20%E5%AE%B9%E5%99%A8%E6%95%B0%E6%8D%AE%E5%8D%B7.html\",\"title\":\"容器数据卷\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"容器数据卷\",\"icon\":\"circle-info\",\"order\":6,\"pageview\":false,\"date\":\"2023-12-03T19:24:48.000Z\",\"comment\":false,\"breadcrumb\":false,\"category\":[\"docker🛥️\"],\"tag\":[\"docker🛥️\"],\"description\":\"1.前言 大家好，我是Leo哥🫣🫣🫣，前面我们学习了Docker的安装以及Docker的基本命令。本篇文章我们学习数据卷有关知识点好了，话不多说让我们开始吧😎😎😎。 2.数据卷相关概念 从docker的理念说起，docker将应用和环境打包成一个镜像，运行镜像（生成容器）就可以访问服务了。\\r如果数据都存在容器中，那么删除容器，数据就会丢失！...\"},\"headers\":[{\"level\":2,\"title\":\"1.前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2.数据卷相关概念\",\"slug\":\"_2-数据卷相关概念\",\"link\":\"#_2-数据卷相关概念\",\"children\":[{\"level\":3,\"title\":\"2.1 什么是数据卷\",\"slug\":\"_2-1-什么是数据卷\",\"link\":\"#_2-1-什么是数据卷\",\"children\":[]},{\"level\":3,\"title\":\"2.2 数据卷命令\",\"slug\":\"_2-2-数据卷命令\",\"link\":\"#_2-2-数据卷命令\",\"children\":[]}]},{\"level\":2,\"title\":\"3.演示\",\"slug\":\"_3-演示\",\"link\":\"#_3-演示\",\"children\":[]},{\"level\":2,\"title\":\"4.挂载本地目录\",\"slug\":\"_4-挂载本地目录\",\"link\":\"#_4-挂载本地目录\",\"children\":[{\"level\":3,\"title\":\"4.1 概述\",\"slug\":\"_4-1-概述\",\"link\":\"#_4-1-概述\",\"children\":[]},{\"level\":3,\"title\":\"4.2 开始挂载\",\"slug\":\"_4-2-开始挂载\",\"link\":\"#_4-2-开始挂载\",\"children\":[]},{\"level\":3,\"title\":\"4.3 核验\",\"slug\":\"_4-3-核验\",\"link\":\"#_4-3-核验\",\"children\":[]}]},{\"level\":2,\"title\":\"5.挂载的三种方式\",\"slug\":\"_5-挂载的三种方式\",\"link\":\"#_5-挂载的三种方式\",\"children\":[]},{\"level\":2,\"title\":\"6.文章参考\",\"slug\":\"_6-文章参考\",\"link\":\"#_6-文章参考\",\"children\":[]},{\"level\":2,\"title\":\"7.总结\",\"slug\":\"_7-总结\",\"link\":\"#_7-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":8.86,\"words\":2657},\"filePathRelative\":\"middleware/docker/container-data-volume.md\",\"localizedDate\":\"2023年12月4日\",\"copyright\":{\"author\":\"LeoJavaer(toleojavaer.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
