export const data = JSON.parse("{\"key\":\"v-0ce3db9e\",\"path\":\"/middleware/docker/09%20Docker%20%20%E5%8F%91%E5%B8%83%E9%95%9C%E5%83%8F%E5%88%B0%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93.html\",\"title\":\"发布镜像到镜像仓库\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"发布镜像到镜像仓库\",\"icon\":\"circle-info\",\"order\":10,\"tag\":[\"docker🛥️\"],\"category\":[\"docker🛥️\"],\"pageview\":false,\"date\":\"2023-12-25T19:42:17.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"1.前言 大家好，我是Leo哥🫣🫣🫣，这篇文章 (hhttps://gaoziman.gitee.io/blogs/middleware/docker/custom-docker-images.html)中，我们学习如果快速通过Dockerfile进行自定义镜像。那我们如果把这些自定义的镜像上传到dockerhub公开出来，供大家使用呢，这篇文章...\"},\"headers\":[{\"level\":2,\"title\":\"1.前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2.注册DockerHub\",\"slug\":\"_2-注册dockerhub\",\"link\":\"#_2-注册dockerhub\",\"children\":[]},{\"level\":2,\"title\":\"3.Docker的安装\",\"slug\":\"_3-docker的安装\",\"link\":\"#_3-docker的安装\",\"children\":[]},{\"level\":2,\"title\":\"4.编写Dockerfile文件\",\"slug\":\"_4-编写dockerfile文件\",\"link\":\"#_4-编写dockerfile文件\",\"children\":[]},{\"level\":2,\"title\":\"5.修改镜像标签\",\"slug\":\"_5-修改镜像标签\",\"link\":\"#_5-修改镜像标签\",\"children\":[]},{\"level\":2,\"title\":\"6.登录到DockerHub\",\"slug\":\"_6-登录到dockerhub\",\"link\":\"#_6-登录到dockerhub\",\"children\":[{\"level\":3,\"title\":\"6.1 指定用户登录\",\"slug\":\"_6-1-指定用户登录\",\"link\":\"#_6-1-指定用户登录\",\"children\":[]},{\"level\":3,\"title\":\"6.2 直接使用docker login登录\",\"slug\":\"_6-2-直接使用docker-login登录\",\"link\":\"#_6-2-直接使用docker-login登录\",\"children\":[]}]},{\"level\":2,\"title\":\"7.推送镜像\",\"slug\":\"_7-推送镜像\",\"link\":\"#_7-推送镜像\",\"children\":[]},{\"level\":2,\"title\":\"8.查看DockerHub\",\"slug\":\"_8-查看dockerhub\",\"link\":\"#_8-查看dockerhub\",\"children\":[]},{\"level\":2,\"title\":\"9.拉取镜像\",\"slug\":\"_9-拉取镜像\",\"link\":\"#_9-拉取镜像\",\"children\":[]},{\"level\":2,\"title\":\"10.相关文献参考\",\"slug\":\"_10-相关文献参考\",\"link\":\"#_10-相关文献参考\",\"children\":[]},{\"level\":2,\"title\":\"11.总结\",\"slug\":\"_11-总结\",\"link\":\"#_11-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":2.67,\"words\":802},\"filePathRelative\":\"middleware/docker/publish-image-to-image-repository.md\",\"localizedDate\":\"2023年12月26日\",\"copyright\":{\"author\":\"LeoJavaer(toleojavaer.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
