export const data = JSON.parse("{\"key\":\"v-3539fb9b\",\"path\":\"/framework/mybaits/mybatis-source/mybatis-source-start.html\",\"title\":\"MyBatis源码初始\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"MyBatis源码初始\",\"icon\":\"circle-info\",\"order\":1,\"tag\":[\"mybaits🐦️\"],\"category\":[\"mybaits🐦️\"],\"pageview\":false,\"date\":\"2023-10-22T16:48:30.000Z\",\"comment\":false,\"description\":\"大家好，我是Leo🫣🫣🫣，从今天开始跟着孙帅老师一起学习MyBatis3的源码学习，这个系列记录着MyBatis3源码学习的笔记和思考，\\r 让我们开始吧😎😎😎。 1. MyBatis回顾 1.1 关于开发环境 下面是笔者本次学习MyBatis源码的开发环境，大家可以进行参考。 ```markdown 1. JDK8 2. IDEA2023....\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://manamn.space/framework/MyBatis/mybatis-source/mybatis-source-start.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLeoJavaer\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"MyBatis源码初始\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"大家好，我是Leo🫣🫣🫣，从今天开始跟着孙帅老师一起学习MyBatis3的源码学习，这个系列记录着MyBatis3源码学习的笔记和思考，\\r 让我们开始吧😎😎😎。 1. MyBatis回顾 1.1 关于开发环境 下面是笔者本次学习MyBatis源码的开发环境，大家可以进行参考。 ```markdown 1. JDK8 2. IDEA2023....\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Leo\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"mybaits🐦️\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-10-22T16:48:30.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"MyBatis源码初始\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-10-22T16:48:30.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Leo\\\",\\\"url\\\":\\\"https://manamn.space/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1. MyBatis回顾\",\"slug\":\"_1-mybatis回顾\",\"link\":\"#_1-mybatis回顾\",\"children\":[{\"level\":3,\"title\":\"1.1 关于开发环境\",\"slug\":\"_1-1-关于开发环境\",\"link\":\"#_1-1-关于开发环境\",\"children\":[]},{\"level\":3,\"title\":\"1.2 Mybatis开发的简单回顾\",\"slug\":\"_1-2-mybatis开发的简单回顾\",\"link\":\"#_1-2-mybatis开发的简单回顾\",\"children\":[]},{\"level\":3,\"title\":\"1.3 搭建MyBatis开发环境\",\"slug\":\"_1-3-搭建mybatis开发环境\",\"link\":\"#_1-3-搭建mybatis开发环境\",\"children\":[]}]},{\"level\":2,\"title\":\"2. MyBatis的核心对象\",\"slug\":\"_2-mybatis的核心对象\",\"link\":\"#_2-mybatis的核心对象\",\"children\":[{\"level\":3,\"title\":\"2.1 MyBatis的核心对象\",\"slug\":\"_2-1-mybatis的核心对象\",\"link\":\"#_2-1-mybatis的核心对象\",\"children\":[]}]},{\"level\":2,\"title\":\"3.总结\",\"slug\":\"_3-总结\",\"link\":\"#_3-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":9.13,\"words\":2740},\"filePathRelative\":\"framework/mybaits/mybatis-source/mybatis-source-start.md\",\"localizedDate\":\"2023年10月23日\",\"copyright\":{\"author\":\"LeoJavaer(toleojavaer.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
