export const data = JSON.parse("{\"key\":\"v-0b0caa64\",\"path\":\"/interview/knowledge-block/star/springaop-aspectj.html\",\"title\":\"SpringAOP和AspectJ有什么关系\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"SpringAOP和AspectJ有什么关系\",\"icon\":\"circle-info\",\"order\":17,\"pageview\":false,\"date\":\"2024-07-09T15:54:24.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"我们知道现在开发都是Spring，讲的最多的也是SpringAOP，在说springAOP前，先了解下AOP是什么？ AOP是通过 “预编译方式” 和 “运行期间动态代理” 实现程序功能的统一维护的一种技术。AOP是一个概念，其实现技术有AspectJ和springAOP，现在对AOP有个清楚的了解了，再来看下AOP中的一些概念。 1. 切面（aspe...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/interview/knowledge-block/star/springaop-aspectj.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"SpringAOP和AspectJ有什么关系\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"我们知道现在开发都是Spring，讲的最多的也是SpringAOP，在说springAOP前，先了解下AOP是什么？ AOP是通过 “预编译方式” 和 “运行期间动态代理” 实现程序功能的统一维护的一种技术。AOP是一个概念，其实现技术有AspectJ和springAOP，现在对AOP有个清楚的了解了，再来看下AOP中的一些概念。 1. 切面（aspe...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-07-09T15:54:24.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"SpringAOP和AspectJ有什么关系\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-07-09T15:54:24.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"基本概念\",\"slug\":\"基本概念\",\"link\":\"#基本概念\",\"children\":[]},{\"level\":3,\"title\":\"他们之间的关系\",\"slug\":\"他们之间的关系\",\"link\":\"#他们之间的关系\",\"children\":[]},{\"level\":3,\"title\":\"使用场景\",\"slug\":\"使用场景\",\"link\":\"#使用场景\",\"children\":[]},{\"level\":3,\"title\":\"实现方式不同\",\"slug\":\"实现方式不同\",\"link\":\"#实现方式不同\",\"children\":[]},{\"level\":3,\"title\":\"基本概念\",\"slug\":\"基本概念-1\",\"link\":\"#基本概念-1\",\"children\":[]},{\"level\":3,\"title\":\"他们之间的关系\",\"slug\":\"他们之间的关系-1\",\"link\":\"#他们之间的关系-1\",\"children\":[]},{\"level\":3,\"title\":\"使用场景\",\"slug\":\"使用场景-1\",\"link\":\"#使用场景-1\",\"children\":[]},{\"level\":3,\"title\":\"实现方式不同\",\"slug\":\"实现方式不同-1\",\"link\":\"#实现方式不同-1\",\"children\":[]}],\"readingTime\":{\"minutes\":7.38,\"words\":2215},\"filePathRelative\":\"interview/knowledge-block/star/springaop-aspectj.md\",\"localizedDate\":\"2024年7月9日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
