export const data = JSON.parse("{\"key\":\"v-41904f13\",\"path\":\"/Linux_linshi/Linux%E5%A6%82%E4%BD%95%E5%B0%86%E6%96%87%E4%BB%B6%E6%88%96%E7%9B%AE%E5%BD%95%E6%89%93%E6%88%90rpm%E5%8C%85%EF%BC%9F%20--%20fpm%E6%89%93%E5%8C%85%E8%AF%A6%E8%A7%A3.html\",\"title\":\"Linux如何将文件或目录打成rpm包？ -- fpm打包详解\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Linux如何将文件或目录打成rpm包？ -- fpm打包详解\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-19T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"seo\":false},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"说明 -- fpm参数及解析\",\"slug\":\"说明-fpm参数及解析\",\"link\":\"#说明-fpm参数及解析\",\"children\":[]},{\"level\":2,\"title\":\"一、安装fpm命令\",\"slug\":\"一、安装fpm命令\",\"link\":\"#一、安装fpm命令\",\"children\":[{\"level\":3,\"title\":\"1.1 安装 ruby 环境\",\"slug\":\"_1-1-安装-ruby-环境\",\"link\":\"#_1-1-安装-ruby-环境\",\"children\":[]},{\"level\":3,\"title\":\"1.2 更换 gem 源为阿里源\",\"slug\":\"_1-2-更换-gem-源为阿里源\",\"link\":\"#_1-2-更换-gem-源为阿里源\",\"children\":[]},{\"level\":3,\"title\":\"1.3 安装 fpm\",\"slug\":\"_1-3-安装-fpm\",\"link\":\"#_1-3-安装-fpm\",\"children\":[]}]},{\"level\":2,\"title\":\"二、将文件打成rpm包\",\"slug\":\"二、将文件打成rpm包\",\"link\":\"#二、将文件打成rpm包\",\"children\":[]},{\"level\":2,\"title\":\"三、安装、卸载rpm包\",\"slug\":\"三、安装、卸载rpm包\",\"link\":\"#三、安装、卸载rpm包\",\"children\":[{\"level\":3,\"title\":\"3.1 安装rpm包\",\"slug\":\"_3-1-安装rpm包\",\"link\":\"#_3-1-安装rpm包\",\"children\":[]},{\"level\":3,\"title\":\"3.2 查找刚刚安装rpm包\",\"slug\":\"_3-2-查找刚刚安装rpm包\",\"link\":\"#_3-2-查找刚刚安装rpm包\",\"children\":[]},{\"level\":3,\"title\":\"3.3 卸载刚刚安装的rpm包\",\"slug\":\"_3-3-卸载刚刚安装的rpm包\",\"link\":\"#_3-3-卸载刚刚安装的rpm包\",\"children\":[]}]},{\"level\":2,\"title\":\"四、错误整理\",\"slug\":\"四、错误整理\",\"link\":\"#四、错误整理\",\"children\":[{\"level\":3,\"title\":\"2.1 ERROR:  Error installing fpm: \\trexml requires Ruby version >= 2.5.0.\",\"slug\":\"_2-1-error-error-installing-fpm-rexml-requires-ruby-version-2-5-0\",\"link\":\"#_2-1-error-error-installing-fpm-rexml-requires-ruby-version-2-5-0\",\"children\":[]},{\"level\":3,\"title\":\"2.2 /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- json (LoadError)\",\"slug\":\"_2-2-usr-share-rubygems-rubygems-core-ext-kernel-require-rb-54-in-require-cannot-load-such-file-json-loaderror\",\"link\":\"#_2-2-usr-share-rubygems-rubygems-core-ext-kernel-require-rb-54-in-require-cannot-load-such-file-json-loaderror\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.77,\"words\":1730},\"filePathRelative\":\"Linux_linshi/Linux如何将文件或目录打成rpm包？ -- fpm打包详解.md\",\"localizedDate\":\"2024年12月19日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
