export const data = JSON.parse("{\"key\":\"v-6873bb68\",\"path\":\"/Linux_linshi/%E3%80%90Linux%E3%80%91Tomcat%E7%AE%80%E4%BB%8B%E5%8F%8A%E4%BA%8C%E8%BF%9B%E5%88%B6%E5%AE%89%E8%A3%85.html\",\"title\":\"【Linux】Tomcat简介及二进制安装\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】Tomcat简介及二进制安装\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"Tomcat\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-18T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"seo\":false,\"head\":[]},\"headers\":[{\"level\":2,\"title\":\"1、Tomcat介绍\",\"slug\":\"_1、tomcat介绍\",\"link\":\"#_1、tomcat介绍\",\"children\":[]},{\"level\":2,\"title\":\"2、Tomcat的安装\",\"slug\":\"_2、tomcat的安装\",\"link\":\"#_2、tomcat的安装\",\"children\":[{\"level\":3,\"title\":\"2.1 安装JDK环境\",\"slug\":\"_2-1-安装jdk环境\",\"link\":\"#_2-1-安装jdk环境\",\"children\":[]},{\"level\":3,\"title\":\"2.2 部署Tomcat\",\"slug\":\"_2-2-部署tomcat\",\"link\":\"#_2-2-部署tomcat\",\"children\":[{\"level\":4,\"title\":\"2.2.1 下载安装包\",\"slug\":\"_2-2-1-下载安装包\",\"link\":\"#_2-2-1-下载安装包\",\"children\":[]},{\"level\":4,\"title\":\"2.2.2 部署Tomcat\",\"slug\":\"_2-2-2-部署tomcat\",\"link\":\"#_2-2-2-部署tomcat\",\"children\":[]},{\"level\":4,\"title\":\"2.2.3 web页面访问\",\"slug\":\"_2-2-3-web页面访问\",\"link\":\"#_2-2-3-web页面访问\",\"children\":[]},{\"level\":4,\"title\":\"2.2.4 二进制安装tomcat相关命令\",\"slug\":\"_2-2-4-二进制安装tomcat相关命令\",\"link\":\"#_2-2-4-二进制安装tomcat相关命令\",\"children\":[]}]},{\"level\":3,\"title\":\"2.3 Tomcat配置文件详解\",\"slug\":\"_2-3-tomcat配置文件详解\",\"link\":\"#_2-3-tomcat配置文件详解\",\"children\":[{\"level\":4,\"title\":\"2.3.1 Tomcat目录详解\",\"slug\":\"_2-3-1-tomcat目录详解\",\"link\":\"#_2-3-1-tomcat目录详解\",\"children\":[]},{\"level\":4,\"title\":\"2.3.2 Tomcat中conf目录中配置文件详解\",\"slug\":\"_2-3-2-tomcat中conf目录中配置文件详解\",\"link\":\"#_2-3-2-tomcat中conf目录中配置文件详解\",\"children\":[]}]}]},{\"level\":2,\"title\":\"相关文章🔅\",\"slug\":\"相关文章🔅\",\"link\":\"#相关文章🔅\",\"children\":[]}],\"readingTime\":{\"minutes\":3.84,\"words\":1151},\"filePathRelative\":\"Linux_linshi/【Linux】Tomcat简介及二进制安装.md\",\"localizedDate\":\"2024年12月18日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
