export const data = JSON.parse("{\"key\":\"v-5c7aaab3\",\"path\":\"/automation/jenkins/%E3%80%90Linux%E3%80%91%E5%9F%BA%E4%BA%8E%20Jenkins%20%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85%E5%B9%B6%E9%83%A8%E7%BD%B2%20Tomcat%20%E7%8E%AF%E5%A2%83_docker%E7%8E%AF%E5%A2%83_PHP%E7%8E%AF%E5%A2%83%20-%20%E5%89%AF%E6%9C%AC.html\",\"title\":\"jenkins的基本配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"在这里插入图片描述 🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿...\"},\"headers\":[{\"level\":2,\"title\":\"1、修改 jenkins 初始密码\",\"slug\":\"_1、修改-jenkins-初始密码\",\"link\":\"#_1、修改-jenkins-初始密码\",\"children\":[]},{\"level\":2,\"title\":\"2、安装 Jenkins 必要插件\",\"slug\":\"_2、安装-jenkins-必要插件\",\"link\":\"#_2、安装-jenkins-必要插件\",\"children\":[]},{\"level\":2,\"title\":\"3、配置 jenkins 并发执行数量\",\"slug\":\"_3、配置-jenkins-并发执行数量\",\"link\":\"#_3、配置-jenkins-并发执行数量\",\"children\":[]},{\"level\":2,\"title\":\"4、配置邮件地址\",\"slug\":\"_4、配置邮件地址\",\"link\":\"#_4、配置邮件地址\",\"children\":[]},{\"level\":2,\"title\":\"传统网站部署的流程\",\"slug\":\"传统网站部署的流程\",\"link\":\"#传统网站部署的流程\",\"children\":[]},{\"level\":2,\"title\":\"主流网站部署的流程\",\"slug\":\"主流网站部署的流程\",\"link\":\"#主流网站部署的流程\",\"children\":[]},{\"level\":2,\"title\":\"Jenkins工作原理及实验准备\",\"slug\":\"jenkins工作原理及实验准备\",\"link\":\"#jenkins工作原理及实验准备\",\"children\":[]},{\"level\":2,\"title\":\"1、配置 git 主机\",\"slug\":\"_1、配置-git-主机\",\"link\":\"#_1、配置-git-主机\",\"children\":[]},{\"level\":2,\"title\":\"2、配置 jenkins 主机\",\"slug\":\"_2、配置-jenkins-主机\",\"link\":\"#_2、配置-jenkins-主机\",\"children\":[]},{\"level\":2,\"title\":\"3、配置 web 主机\",\"slug\":\"_3、配置-web-主机\",\"link\":\"#_3、配置-web-主机\",\"children\":[]},{\"level\":2,\"title\":\"4、新建 Maven 项目\",\"slug\":\"_4、新建-maven-项目\",\"link\":\"#_4、新建-maven-项目\",\"children\":[]},{\"level\":2,\"title\":\"5、验证 Jenkins 自动打包部署结果\",\"slug\":\"_5、验证-jenkins-自动打包部署结果\",\"link\":\"#_5、验证-jenkins-自动打包部署结果\",\"children\":[]},{\"level\":2,\"title\":\"1、安装 docker-ce\",\"slug\":\"_1、安装-docker-ce\",\"link\":\"#_1、安装-docker-ce\",\"children\":[]},{\"level\":2,\"title\":\"2、阿里云镜像加速器\",\"slug\":\"_2、阿里云镜像加速器\",\"link\":\"#_2、阿里云镜像加速器\",\"children\":[]},{\"level\":2,\"title\":\"3、构建 tomcat 基础镜像\",\"slug\":\"_3、构建-tomcat-基础镜像\",\"link\":\"#_3、构建-tomcat-基础镜像\",\"children\":[]},{\"level\":2,\"title\":\"4、构建一个 Maven 项目\",\"slug\":\"_4、构建一个-maven-项目\",\"link\":\"#_4、构建一个-maven-项目\",\"children\":[]},{\"level\":2,\"title\":\"基于 rsync 部署\",\"slug\":\"基于-rsync-部署\",\"link\":\"#基于-rsync-部署\",\"children\":[]},{\"level\":2,\"title\":\"基于 ansible 部署\",\"slug\":\"基于-ansible-部署\",\"link\":\"#基于-ansible-部署\",\"children\":[]}],\"readingTime\":{\"minutes\":14.95,\"words\":4484},\"filePathRelative\":\"automation/jenkins/【Linux】基于 Jenkins 自动打包并部署 Tomcat 环境_docker环境_PHP环境 - 副本.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
