<template><div><blockquote>
<p>👨‍🎓<strong>博主简介</strong></p>
<p>  🏅<a href="https://blog.csdn.net/liu_chen_yang?type=blog" target="_blank" rel="noopener noreferrer">云计算领域优质创作者</a><br>
  🏅<a href="https://bbs.huaweicloud.com/community/myblog" target="_blank" rel="noopener noreferrer">华为云开发者社区专家博主</a><br>
  🏅<a href="https://developer.aliyun.com/my?spm=a2c6h.13148508.setting.3.21fc4f0eCmz1v3#/article?_k=zooqoz" target="_blank" rel="noopener noreferrer">阿里云开发者社区专家博主</a><br>
💊<strong>交流社区：</strong><a href="https://bbs.csdn.net/forums/lcy" target="_blank" rel="noopener noreferrer">运维交流社区</a> 欢迎大家的加入！<br>
🐋 希望大家多多支持，我们一起进步！😄<br>
🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗</p>
</blockquote>
<hr>
<h2 id="问题" tabindex="-1"><a class="header-anchor" href="#问题"><span>问题：</span></a></h2>
<blockquote>
<p>  因为最近要打镜像，首先需要看一下该机器是否可以拉取到镜像，我就开始试拉取镜像，结果报错一层有一层；拉了一天都没有拉取到想要的镜像，就很气愤；最后找了很多文章以及报错的解决方式终于找到一个成功的了；<br>
我就拿其一来举例，其中有一个报错是这样的；</p>
</blockquote>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@localhost docker]# docker pull qiushenjie/cuda11.1-cudnn8-devel-ubuntu18.04-python3.6:latest</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">latest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pulling</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> qiushenjie/cuda11.1-cudnn8-devel-ubuntu18.04-python3.6</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">6e0aa5e7af40:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloading</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [==================================================>]  8.753MB/8.753MB</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d47239a868b3:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">49cbb10cca85:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4450dd082e0f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">c0471462e31b:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">e26abf45abc8:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d044dd425955:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">03443386476a:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloading</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [==================================================>]  1.511GB/1.511GB</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">1221fea730a2:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">9b0547807030:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloading</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07352373c41d:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">459b54df8da1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloading</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4743a36bdb91:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Retrying</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> second</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">7ad0074e2854:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">75822f5b5ee1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloading</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [==================================================>]  89.39kB/89.39kB</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">read</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tcp</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 172.16.11.202:42874</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">104.18.125.25:443:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> read:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> connection</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reset</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> by</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> peer</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="报错原因" tabindex="-1"><a class="header-anchor" href="#报错原因"><span>报错原因：</span></a></h2>
<blockquote>
<p>  因为我们下载的镜像是外网的镜像资源，所以下载的速度会非常的慢，甚至大概率下载时会报错，所以需要我们配置一个国内的服务器镜像地址，国内服务器镜像地址有很多，这里咱们就说一下阿里镜像加速器的配置方法。</p>
</blockquote>
<h2 id="解决方式" tabindex="-1"><a class="header-anchor" href="#解决方式"><span>解决方式：</span></a></h2>
<blockquote>
<p>  找了很久找到了一个好的解决方式就是：<font color=teal><strong>配置阿里镜像加速器方法</strong></font></p>
</blockquote>
<p>1、访问阿里云官网：<a href="https://promotion.aliyun.com/ntms/act/kubernetes.html" target="_blank" rel="noopener noreferrer">阿里云官网</a>     并登录官网：</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517319.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>2、登录进来点击控制台：</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517666.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>3、点击左上方的导航栏，在搜索框搜索容器镜像服务</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517962.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>4、点击 镜像工具---镜像加速器</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517558.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>5、复制镜像加速器地址，按照操作文档，找到对应平台的文档进行操作</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517544.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>6、返回服务器，新建 <font color=red> <strong>/etc/docker</strong> </font>目录</p>
<ul>
<li>已有就不用创建了</li>
</ul>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">mkdir</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -p</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /etc/docker</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>7、将下载的镜像加速器加到 <font color=red><strong>daemon.json</strong> </font>配置文件中；</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@localhost docker]# sudo tee /etc/docker/daemon.json &#x3C;&#x3C;-</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">'EOF'</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">{</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  "registry-mirrors": ["https://ofads5sdl5c.mirror.aliyuncs.com"]</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">}</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">EOF</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>8、重新加载配置文件+重启docker服务</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#重新加载配置文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">systemctl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> daemon-reload</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#重启docker服务</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">systemctl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> restart</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>9、重新拉取镜像</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@localhost docker]# docker pull qiushenjie/cuda11.1-cudnn8-devel-ubuntu18.04-python3.6:latest</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">latest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pulling</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> qiushenjie/cuda11.1-cudnn8-devel-ubuntu18.04-python3.6</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">6e0aa5e7af40:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d47239a868b3:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">49cbb10cca85:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4450dd082e0f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">c0471462e31b:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">e26abf45abc8:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d044dd425955:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">03443386476a:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">1221fea730a2:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">9b0547807030:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">07352373c41d:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">459b54df8da1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4743a36bdb91:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">7ad0074e2854:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">75822f5b5ee1:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Download</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Digest：</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> a256:c358e72e100ab493a0304bda35e6f239db2ec8c9bb836d8a427ac34307d074ed</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Status：</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloadednewer</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> image</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> qiushenjie/cuda11.1-cudnn8-devel-ubuntu18.04-python3.6:latest</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161517545.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>这样就下载拉取完成了；</p>
</div></template>


