import comp from "D:/JAVA项目/ToLiucyLinux-test/src/.vuepress/.temp/pages/document/Linux/Linux网络管理之网卡、网络接口开关设置.html.vue"
const data = JSON.parse("{\"path\":\"/document/Linux/Linux%E7%BD%91%E7%BB%9C%E7%AE%A1%E7%90%86%E4%B9%8B%E7%BD%91%E5%8D%A1%E3%80%81%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E5%BC%80%E5%85%B3%E8%AE%BE%E7%BD%AE.html\",\"title\":\"Linux网络管理之网卡、网络接口开关设置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Linux网络管理之网卡、网络接口开关设置\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-19T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"gitInclude\":[],\"description\":\"ifup 开启网卡-激活网络接口 ifup命令用于激活指定的网络接口。ifup命令会去读取/etc/sysconfig/network-scripts/目录下的相关网络接口的配置文件，并根据配置文件的内容来激活该网络接口。 注意：网络接口名称必须是/etc/sysconfig/network-scripts/目录配置文件中设置的才可以。如果使用ifco...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/document/Linux/Linux%E7%BD%91%E7%BB%9C%E7%AE%A1%E7%90%86%E4%B9%8B%E7%BD%91%E5%8D%A1%E3%80%81%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E5%BC%80%E5%85%B3%E8%AE%BE%E7%BD%AE.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Linux网络管理之网卡、网络接口开关设置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"ifup 开启网卡-激活网络接口 ifup命令用于激活指定的网络接口。ifup命令会去读取/etc/sysconfig/network-scripts/目录下的相关网络接口的配置文件，并根据配置文件的内容来激活该网络接口。 注意：网络接口名称必须是/etc/sysconfig/network-scripts/目录配置文件中设置的才可以。如果使用ifco...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-19T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Linux网络管理之网卡、网络接口开关设置\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-19T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"𝑴𝒓.𝑳𝒊𝒖𝒄𝒚\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"ifup 开启网卡-激活网络接口\",\"slug\":\"ifup-开启网卡-激活网络接口\",\"link\":\"#ifup-开启网卡-激活网络接口\",\"children\":[]},{\"level\":2,\"title\":\"ifdown 关闭网卡– 禁用网络接口\",\"slug\":\"ifdown-关闭网卡–-禁用网络接口\",\"link\":\"#ifdown-关闭网卡–-禁用网络接口\",\"children\":[]}],\"readingTime\":{\"minutes\":1.32,\"words\":396},\"filePathRelative\":\"document/Linux/Linux网络管理之网卡、网络接口开关设置.md\",\"localizedDate\":\"2024年12月19日\",\"excerpt\":\"<h2>ifup 开启网卡-激活网络接口</h2>\\n<p>ifup命令用于激活指定的网络接口。ifup命令会去读取/etc/sysconfig/network-scripts/目录下的相关网络接口的配置文件，并根据配置文件的内容来激活该网络接口。</p>\\n<p>注意：网络接口名称必须是/etc/sysconfig/network-scripts/目录配置文件中设置的才可以。如果使用ifconfig命令改变了网络接口后，ifup命令就不会识别了。因为ifup命令会对比当前网络的参数与/etc/sysconfig/network-scripts/中配置文件的内容是否相符。</p>\\n<p><strong></strong></p>\",\"copyright\":\"著作权归 Mr.Liucy 所有，基于 MIT 协议，原文链接：https://liuchenyang.top\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
