<template><div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007644.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<blockquote>
<p>👨‍🎓<strong>博主简介</strong></p>
<p>  🏅<a href="https://blog.csdn.net/liu_chen_yang?type=blog" target="_blank" rel="noopener noreferrer">云计算领域优质创作者</a><br>
  🏅<a href="https://bbs.huaweicloud.com/community/myblog" target="_blank" rel="noopener noreferrer">华为云开发者社区专家博主</a><br>
  🏅<a href="https://developer.aliyun.com/my?spm=a2c6h.13148508.setting.3.21fc4f0eCmz1v3#/article?_k=zooqoz" target="_blank" rel="noopener noreferrer">阿里云开发者社区专家博主</a><br>
💊<strong>交流社区：</strong><a href="https://bbs.csdn.net/forums/lcy" target="_blank" rel="noopener noreferrer">运维交流社区</a> 欢迎大家的加入！<br>
🐋 希望大家多多支持，我们一起进步！😄<br>
🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗</p>
</blockquote>
<hr>
<h2 id="nvidia-smi简介" tabindex="-1"><a class="header-anchor" href="#nvidia-smi简介"><span>nvidia-smi简介</span></a></h2>
<h3 id="_1、什么是nvidia-smi" tabindex="-1"><a class="header-anchor" href="#_1、什么是nvidia-smi"><span>1、什么是nvidia-smi</span></a></h3>
<blockquote>
<p>nvidia-smi是nvidia 的系统管理界面 ，其中smi是 <strong>System management interface</strong> 的缩写，它可以收集各种级别的信息，查看显存使用情况，显卡的温度... ...。此外, 可以启用和禁用 GPU 配置选项 (如 ECC 内存功能)。</p>
</blockquote>
<h3 id="_2、介绍nvidia-smi" tabindex="-1"><a class="header-anchor" href="#_2、介绍nvidia-smi"><span>2、介绍nvidia-smi</span></a></h3>
<blockquote>
<p>nvidia-sim简称NVSMI，提供监控GPU使用情况和更改GPU状态的功能，是一个跨平台工具，支持所有标准的NVIDIA驱动程序支持的Linux和WindowsServer 2008 R2 开始的64位系统。这个工具是N卡驱动附带的，只要使用nvidia显卡，完成安装驱动就会有nvidia-smi命令；</p>
</blockquote>
<h2 id="nvidia-smi命令详解" tabindex="-1"><a class="header-anchor" href="#nvidia-smi命令详解"><span>nvidia-smi命令详解</span></a></h2>
<h3 id="nvidia-smi-表格参数详解" tabindex="-1"><a class="header-anchor" href="#nvidia-smi-表格参数详解"><span>nvidia-smi 表格参数详解</span></a></h3>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201008125.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">+-----------------------------------------------------------------------------+</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">NVIDIA-SMI</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 515.57</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Version:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 515.57</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       CUDA</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Version:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 11.7</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-------------------------------+----------------------+----------------------+</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        Persistence-M</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Bus-Id</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        Disp.A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Volatile</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Uncorr.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ECC</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Fan</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Temp</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Perf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Pwr:Usage/Cap</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|         </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Memory-Usage</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU-Util</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Compute</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|                               |                      |               </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">MIG</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">===============================+======================+======================</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|   </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  NVIDIA</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> GeForce</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ...</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Off</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">00000000:65:00.0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Off</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |                  </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">N/A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">30%</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   22C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    P8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     3W</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 350W</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |   </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">9815MiB</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 12288MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |      </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0%</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      Default</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|                               |                      |                  </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">N/A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">+-------------------------------+----------------------+----------------------+</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                                                                               </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">+-----------------------------------------------------------------------------+</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Processes:</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                                                                  |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|  </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   GI</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   CI</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        PID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   Type</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   Process</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                  GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Memory</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|        </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                                                   Usage</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=============================================================================</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|    </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   N/A</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  N/A</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">     37593</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   java</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                             2869MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|    </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   N/A</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  N/A</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">     48477</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   python3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                          2779MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">+-----------------------------------------------------------------------------+</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p> <br>
 </p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">NVIDIA-SMI</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 515.57</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Version:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 515.57</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       CUDA</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Version:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 11.7</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     |</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><blockquote>
<p>NVIDIA-SMI 515.57   #GRID版本<br>
Driver Version: 515.57  #驱动版本<br>
CUDA Version: 11.7   #CUDA最高支持的版本</p>
</blockquote>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        Persistence-M</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Bus-Id</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        Disp.A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Volatile</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Uncorr.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ECC</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Fan</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Temp</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Perf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Pwr:Usage/Cap</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|         </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Memory-Usage</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU-Util</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Compute</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> M.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">===============================+======================+======================</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|   </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  NVIDIA</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> GeForce</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ...</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  Off</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">00000000:65:00.0</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Off</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |                  </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">N/A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">30%</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   22C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    P8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     3W</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 350W</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |   </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">9815MiB</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 12288MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |      </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0%</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      Default</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p><code v-pre>|===============================+======================+======================|</code><br>
为分隔符：上下两行是对应关系，上1对下1，上2对下2<br>
 </p>
<ul>
<li>GPU         #本机中的GPU编号,（多块显卡的时候，编号从0开始）图上GPU的编号为：0。</li>
<li>Fan         #风扇转速（0%-100%）；N/A表示没有风扇；err表示风扇可能损坏；图上表示风扇转速为：30%。</li>
<li>Name        #GPU类型（显卡型号），图上GPU的类型为：NVIDIA GeForce RTX 3080 Ti。</li>
<li>Temp         #GPU的温度（GPU温度过高会导致GPU的频率下降），单位摄氏度C；图上温度为：22C。</li>
<li>Perf         #GPU的性能状态，从P0（最大性能）到P12（最小性能），图上是：P8</li>
<li>Persistence-M    #持续模式的状态，持续模式虽然耗能大，但是在新的GPU应用启动时花费的时间更少，图上显示的是：off</li>
<li>Pwr:Usage/Cap    #能耗表示，Usage：用了多少，Cap总共多少；图上Usage显示：3W，Cap显示：350W。</li>
<li>Bus-Id        #GPU总线相关显示，domain：bus：device.function</li>
<li>Disp.A        #Display Active ，表示GPU的显示是否初始化</li>
<li>Memory-Usage    #内存使用率</li>
<li>Volatile GPU-Util    #GPU使用率</li>
<li>Uncorr. ECC      #关于ECC的东西，是否开启错误检查和纠正技术，0/disabled,1/enabled</li>
<li>Compute M      #计算模式，0/DEFAULT,1/EXCLUSIVE_PROCESS,2/PROHIBITED</li>
</ul>
</blockquote>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">| </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Processes:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                                                       GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Memory</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|  </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">GPU</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       PID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   Type</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   Process</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                             Usage</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=============================================================================</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|    </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">0</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       762</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   java</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                                        1995MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">|    </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">1</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       354</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      C</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   python3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                                     2101MiB</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p><code v-pre>|=============================================================================|</code><br>
为分隔符：分隔符上面对应下面的所有<br>
 </p>
<ul>
<li>Processes       #显示每个进程占用的显存使用率、进程号、占用的哪个GPU。<br>
 </li>
<li>GPU          #当前进程占用的那块显卡。</li>
<li>PID          #当前进程的PID，可使用ps -ef | grep PID 查看详细命令。</li>
<li>Type          #当前进程的运行状态。</li>
<li>Process name     #当前进程的运行主命令。</li>
<li>GPU Memory Usage   #该进程占用的显存。</li>
</ul>
</blockquote>
<h3 id="nvidia-smi-help命令详解" tabindex="-1"><a class="header-anchor" href="#nvidia-smi-help命令详解"><span>nvidia-smi --help命令详解</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">列表选项：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-L</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#列出所有可用的 NVIDIA 设备</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-B</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#列出所有被拉入黑名单的NVIDIA设备</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">查询选项：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-q</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#查询显示GPUnvidia的相关信息</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">配合选项：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-u、</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --unit</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> #显示单位属性，而不是GPU属性。</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-i、</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --id</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#以特定GPU或单元为目标。可指定显卡编号</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">--format</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#指定输出的格式csv</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">--filename</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#输入csv文件，--filename=后跟自定义csv文件名；</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">--query-gpu</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#指定输出的字段，后可跟timestamp时间、name，</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-x、</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --xml</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#格式生成xml输出。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-l</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#持续刷新显存状态</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-lms</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#循环动态显示;每毫秒</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">--dtd</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#显示xml输出时，嵌入dtd。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">-d、</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --display</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#仅显示选定信息：MEMORY，</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="列出所有可用的-nvidia-设备" tabindex="-1"><a class="header-anchor" href="#列出所有可用的-nvidia-设备"><span>列出所有可用的 NVIDIA 设备</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -L</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007621.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<blockquote>
<p>作用：可用作统计服务器中的显卡数量。</p>
</blockquote>
<h4 id="列出所有被拉入黑名单的nvidia设备" tabindex="-1"><a class="header-anchor" href="#列出所有被拉入黑名单的nvidia设备"><span>列出所有被拉入黑名单的NVIDIA设备</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -B</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007457.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<blockquote>
<p><code v-pre>No blacklisted devices found.</code> 未找到列入黑名单的设备。</p>
</blockquote>
<h4 id="查询nvidiagpu的相关信息" tabindex="-1"><a class="header-anchor" href="#查询nvidiagpu的相关信息"><span>查询nvidiaGPU的相关信息</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -q</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007437.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="持续刷新显存状态" tabindex="-1"><a class="header-anchor" href="#持续刷新显存状态"><span>持续刷新显存状态</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#每两秒刷新一次显存状态</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -l</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>也可用<code v-pre>watch -n 1 nvidia-smi   #1秒刷新一次显存状态</code></p>
</blockquote>
<h3 id="查询所有的csv文件-query-gpu可使用的字段及字段说明、实例" tabindex="-1"><a class="header-anchor" href="#查询所有的csv文件-query-gpu可使用的字段及字段说明、实例"><span>查询所有的csv文件<code v-pre>--query-gpu</code>可使用的字段及字段说明、实例</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#查询可使用的所有字段</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --help-query-gpu</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">timestamp</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#查询位置的时间戳，格式为“YYYY/MM/DD HH:MM:SS.msec”	；	nvidia-smi --format=csv,noheader --query-gpu=timestamp</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">memory.total</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#查询已安装的GPU显存总数。								nvidia-smi --format=csv,noheader --query-gpu=memory.total</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">memory.used</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#查询已安装的GPU显存使用率。							nvidia-smi --format=csv,noheader --query-gpu=memory.used</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">memory.free</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#查询已安装的GPU剩余显存。								nvidia-smi --format=csv,noheader --query-gpu=memory.free</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">driver_version</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#查询已安装的NVIDIA显示器驱动程序的版本；					nvidia-smi --format=csv,noheader --query-gpu=driver_version</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">index</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">				#输出显卡的编号：										nvidia-smi --format=csv,noheader --query-gpu=index</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pstate</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">				#GPU的当前性能状态。状态范围从P0(最大性能)到P12(最小性能)	nvidia-smi --format=csv,noheader --query-gpu=pstate</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">power.draw</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#显存功耗，对应Pwr：Usage使用：							nvidia-smi --format=csv,noheader --query-gpu=power.draw</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">temperature.gpu</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#输出GPU温度，核心GPU温度。							nvidia-smi --format=csv,noheader --query-gpu=index,temperature.gpu | sed -e "s#, #卡温度为：#g" -e 's#$#°C#g'</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">fan.speed</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#输出GPU风扇转速。									nvidia-smi --format=csv,noheader --query-gpu=index,fan.speed | sed "s#, #卡风扇转速为：#g"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">utilization.gpu</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#输出GPU的使用率：									nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">utilization.memory  #输出显存的使用率：</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">									nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv,noheader</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=utilization.memory</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">count</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">				#查询位置的时间戳，格式为“YYYY/MM/DD HH:MM:SS.msec”；	nvidia-smi --format=csv,noheader --query-gpu=count</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"name"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "gpu_name"</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#查询显卡型号，适用于所有产品；												nvidia-smi --format=csv,noheader --query-gpu=name,gpu_name</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"serial"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "gpu_serial"</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#该编号与每个板上实际打印的序列号相匹配。它是全局唯一的不可变字母数字值。			nvidia-smi --format=csv,noheader --query-gpu=serial,gpu_serial</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"uuid"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "gpu_uuid"</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#此值是GPU的全局唯一不可变字母数字标识符。它与电路板上的任何物理标签都不对应。		nvidia-smi --format=csv,noheader --query-gpu=uuid,gpu_uuid</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"pci.bus_id"</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">or</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"gpu_bus_id"</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#PCI总线id为“域：总线：设备.功能”，十六进制。									nvidia-smi --format=csv,noheader --query-gpu=pci.bus_id,gpu_bus_id</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pci.domain</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#PCI域名，十六进制。									nvidia-smi --format=csv,noheader --query-gpu=pci.domain</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pci.bus</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">				#PCI总线编号，十六进制。								nvidia-smi --format=csv,noheader --query-gpu=pci.bus</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pci.device</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#PCI设备编号，十六进制。								nvidia-smi --format=csv,noheader --query-gpu=pci.device</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pci.device_id</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#PCI供应商设备id，十六进制								nvidia-smi --format=csv,noheader --query-gpu=pci.device_id</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pci.sub_device_id</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">	#PCI子系统id，十六进制									nvidia-smi --format=csv,noheader --query-gpu=pci.sub_device_id</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vbios_version</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#GPU板的BIOS。										nvidia-smi --format=csv,noheader --query-gpu=vbios_version</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">inforom.oem</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#OEM配置数据的版本。									nvidia-smi --format=csv,noheader --query-gpu=inforom.oem</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">inforom.ecc</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">			#ECC记录数据的版本。									nvidia-smi --format=csv,noheader --query-gpu=inforom.ecc</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">driver_model.current</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#当前使用的驱动程序模型。在Linux上始终为“N/A”		nvidia-smi --format=csv,noheader --query-gpu=driver_model.current</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">accounting.buffer_size</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">		#循环缓冲区的大小，该缓冲区包含可查询会计统计信息的进程列表。这是在有关最旧进程的信息被有关新进程的信息覆盖之前，将为其存储记帐信息的最大进程数		nvidia-smi --format=csv --query-gpu=accounting.buffer_size</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="持续监控nvidia-smi结果写入自定义csv文件-并指定写入文件的监控字段" tabindex="-1"><a class="header-anchor" href="#持续监控nvidia-smi结果写入自定义csv文件-并指定写入文件的监控字段"><span>持续监控nvidia-smi结果写入自定义csv文件，并指定写入文件的监控字段</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -l</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --filename=report.csv</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=timestamp,name,index,utilization.gpu,memory.total,memory.used,memory.free,power.draw</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><blockquote>
<p><code v-pre>-l</code>      #隔多久记录一次，我们写的是每秒记录一次。<br>
<code v-pre>--format</code>   #结果记录文件格式是csv类型。（csv）<br>
<code v-pre>--filename</code>  #结果记录文件的名字。（report.csv）<br>
<code v-pre>--query-gpu</code>  #都记录哪些数据到csv文件中；<br>
  <code v-pre>timestamp</code>     #输出每块显卡的时间戳：<code v-pre>nvidia-smi --format=csv --query-gpu=timestamp</code><br>
  <code v-pre>name</code>        #输出显卡的型号（名称）：<code v-pre>nvidia-smi --format=csv --query-gpu=name</code><br>
  <code v-pre>index</code>       #输出显卡的编号：<code v-pre>nvidia-smi --format=csv --query-gpu=index</code><br>
  <code v-pre>utilization.gpu</code>  #输出GPU的使用率：<code v-pre>nvidia-smi --format=csv --query-gpu=utilization.gpu</code><br>
  <code v-pre>memory.total</code>    #显存大小，输出总显存值：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.total</code><br>
  <code v-pre>memory.used</code>     #显存大小，输出使用了多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.used</code><br>
  <code v-pre>memory.free</code>     #显存大小，输出剩余多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.free</code>；不太准，建议使用：总显存-使用显存来计算；<br>
  <code v-pre>power.draw</code>     #显存功耗，对应Pwr：Usage使用：<code v-pre>nvidia-smi --format=csv --query-gpu=power.draw</code></p>
</blockquote>
<h4 id="持续监控nvidia-smi结果为csv类型并双重重定向到csv文件中-并指定写入文件的监控字段" tabindex="-1"><a class="header-anchor" href="#持续监控nvidia-smi结果为csv类型并双重重定向到csv文件中-并指定写入文件的监控字段"><span>持续监控nvidia-smi结果为csv类型并双重重定向到csv文件中，并指定写入文件的监控字段</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -lms</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=timestamp,pstate,temperature.gpu,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tee</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> gpu-log.csv</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><blockquote>
<p><code v-pre>-lms</code>     #循环动态显示;每毫秒<br>
<code v-pre>--query-gpu</code>  #都记录哪些数据到csv文件中；<br>
  <code v-pre>timestamp</code>     #输出每块显卡的时间戳：<code v-pre>nvidia-smi --format=csv --query-gpu=timestamp</code><br>
  <code v-pre>pstate</code>     #输出GPU的性能状态：<code v-pre>nvidia-smi --format=csv --query-gpu=pstate</code><br>
  <code v-pre>temperature.gpu</code>     #输出GPU的显卡温度：<code v-pre>nvidia-smi --format=csv --query-gpu=temperature.gpu</code><br>
  <code v-pre>utilization.gpu</code>  #输出GPU的使用率：<code v-pre>nvidia-smi --format=csv --query-gpu=utilization.gpu</code><br>
  <code v-pre>utilization.memory</code>  #输出显存的使用率：<code v-pre>nvidia-smi --format=csv --query-gpu=utilization.memory</code><br>
  <code v-pre>memory.total</code>    #显存大小，输出总显存值：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.total</code><br>
  <code v-pre>memory.used</code>     #显存大小，输出使用了多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.used</code><br>
  <code v-pre>memory.free</code>     #显存大小，输出剩余多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.free</code>；不太准，建议使用：总显存-使用显存来计算；<br>
<code v-pre>--format</code>   #结果记录文件格式是csv类型。（csv）<br>
<code v-pre>tee</code>      #双重重定向到gpu-log.csv文件中。</p>
</blockquote>
<h4 id="指定0显卡输出csv类型的显存总空间及使用空间和剩余空间" tabindex="-1"><a class="header-anchor" href="#指定0显卡输出csv类型的显存总空间及使用空间和剩余空间"><span>指定0显卡输出csv类型的显存总空间及使用空间和剩余空间</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -i</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">  --query-gpu=memory.total,memory.used,memory.free</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><blockquote>
<p><code v-pre>-i</code>       #指定显卡编号；不使用<code v-pre>-i</code>，默认是显示所有的显卡型号的数据；<code v-pre>nvidia-smi --format=csv  --query-gpu=memory.total,memory.used,memory.free</code><br>
<code v-pre>--format</code>    #结果记录文件格式是csv类型。（csv）<br>
<code v-pre>--query-gpu</code>  #都记录哪些数据到csv文件中；<br>
  <code v-pre>memory.total</code>    #显存大小，输出总显存值：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.total</code><br>
  <code v-pre>memory.used</code>     #显存大小，输出使用了多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.used</code><br>
  <code v-pre>memory.free</code>     #显存大小，输出剩余多少显存：<code v-pre>nvidia-smi --format=csv --query-gpu=memory.free</code>；不太准，建议使用：总显存-使用显存来计算；</p>
</blockquote>
<h4 id="查询所有的csv文件-format可使用的字段及字段说明、实例" tabindex="-1"><a class="header-anchor" href="#查询所有的csv文件-format可使用的字段及字段说明、实例"><span>查询所有的csv文件<code v-pre>--format</code>可使用的字段及字段说明、实例</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">csv</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">			文件格式</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">			vidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=memory.total</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">noheader</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">	去除文件头部标题</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">	vidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv,noheader</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=memory.total</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nounits</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">		去除单位，比如MiB</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">	nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv,noheader,nounits</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=memory.total</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="查询总显存不带头部标题" tabindex="-1"><a class="header-anchor" href="#查询总显存不带头部标题"><span>查询总显存不带头部标题</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv,noheader</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=memory.total</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007130.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="查询总显存不带头部标题并且不带单位" tabindex="-1"><a class="header-anchor" href="#查询总显存不带头部标题并且不带单位"><span>查询总显存不带头部标题并且不带单位</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">nvidia-smi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=csv,noheader,nounits</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --query-gpu=memory.total</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412201007634.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="附加-计算某显卡的剩余显存脚本" tabindex="-1"><a class="header-anchor" href="#附加-计算某显卡的剩余显存脚本"><span>附加：计算某显卡的剩余显存脚本</span></a></h2>
<blockquote>
<p>下载地址：<a href="https://download.csdn.net/download/liu_chen_yang/87364591?spm=1001.2014.3001.5503" target="_blank" rel="noopener noreferrer">计算显卡的剩余显存脚本：nvidia.sh</a><br>
下载时记得看下面的说明和用法哈；<br>
注▲：没有积分可购买时，可私信我发你；但是还是需要进去看一下说明和用法，保证能够顺利使用。</p>
</blockquote>
</div></template>


