export const data = JSON.parse("{\"key\":\"v-06047ecb\",\"path\":\"/knowledge-block/star/15%20%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3JSON%E5%8F%8A%E5%85%B6%E5%9C%A8Java%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8.html\",\"title\":\"深入理解JSON及其在Java中的应用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"1.什么是JSON 在现代的Web开发中，JSON（JavaScript Object Notation）扮演了极其重要的角色。它是一种轻量级的数据交换格式，由于其易于阅读和编写，同时也易于机器解析和生成，因此广泛应用于网络数据交换和配置文件。 JSON: JavaScript Object Notation(JavaScript 对象表示法) JSO...\"},\"headers\":[{\"level\":2,\"title\":\"1.什么是JSON\",\"slug\":\"_1-什么是json\",\"link\":\"#_1-什么是json\",\"children\":[]},{\"level\":2,\"title\":\"2.JSON语法\",\"slug\":\"_2-json语法\",\"link\":\"#_2-json语法\",\"children\":[]},{\"level\":2,\"title\":\"3.认识JSON分支\",\"slug\":\"_3-认识json分支\",\"link\":\"#_3-认识json分支\",\"children\":[{\"level\":3,\"title\":\"3.1 JSON字符串\",\"slug\":\"_3-1-json字符串\",\"link\":\"#_3-1-json字符串\",\"children\":[]},{\"level\":3,\"title\":\"3.2 JSON对象\",\"slug\":\"_3-2-json对象\",\"link\":\"#_3-2-json对象\",\"children\":[]},{\"level\":3,\"title\":\"3.3 JSON数组\",\"slug\":\"_3-3-json数组\",\"link\":\"#_3-3-json数组\",\"children\":[]}]},{\"level\":2,\"title\":\"4.JSONObject\",\"slug\":\"_4-jsonobject\",\"link\":\"#_4-jsonobject\",\"children\":[{\"level\":3,\"title\":\"4.1 功能特点\",\"slug\":\"_4-1-功能特点\",\"link\":\"#_4-1-功能特点\",\"children\":[]},{\"level\":3,\"title\":\"4.2 代码示例\",\"slug\":\"_4-2-代码示例\",\"link\":\"#_4-2-代码示例\",\"children\":[]}]},{\"level\":2,\"title\":\"5.JSONArray\",\"slug\":\"_5-jsonarray\",\"link\":\"#_5-jsonarray\",\"children\":[{\"level\":3,\"title\":\"5.1 特点\",\"slug\":\"_5-1-特点\",\"link\":\"#_5-1-特点\",\"children\":[]},{\"level\":3,\"title\":\"5.2 常用方法\",\"slug\":\"_5-2-常用方法\",\"link\":\"#_5-2-常用方法\",\"children\":[]},{\"level\":3,\"title\":\"示例代码\",\"slug\":\"示例代码\",\"link\":\"#示例代码\",\"children\":[]},{\"level\":3,\"title\":\"5.3 应用场景\",\"slug\":\"_5-3-应用场景\",\"link\":\"#_5-3-应用场景\",\"children\":[]}]},{\"level\":2,\"title\":\"6.FastJson的应用\",\"slug\":\"_6-fastjson的应用\",\"link\":\"#_6-fastjson的应用\",\"children\":[{\"level\":3,\"title\":\"6.1 FastJson的优点\",\"slug\":\"_6-1-fastjson的优点\",\"link\":\"#_6-1-fastjson的优点\",\"children\":[]},{\"level\":3,\"title\":\"6.2 在Java中引用FastJson\",\"slug\":\"_6-2-在java中引用fastjson\",\"link\":\"#_6-2-在java中引用fastjson\",\"children\":[]},{\"level\":3,\"title\":\"6.4 示例代码\",\"slug\":\"_6-4-示例代码\",\"link\":\"#_6-4-示例代码\",\"children\":[]}]},{\"level\":2,\"title\":\"7.JSON格式化网站\",\"slug\":\"_7-json格式化网站\",\"link\":\"#_7-json格式化网站\",\"children\":[]}],\"readingTime\":{\"minutes\":8.16,\"words\":2448},\"filePathRelative\":\"knowledge-block/star/deeply-understand-jsonand-application-in-java.md\",\"copyright\":{\"author\":\"LeoJavaer(toleojavaer.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
