<template><div><blockquote>
<p>🍁<strong>博主简介</strong></p>
<p>  🏅<a href="https://blog.csdn.net/liu_chen_yang?type=blog" target="_blank" rel="noopener noreferrer">云计算领域优质创作者</a><br>
  🏅<a href="https://bbs.huaweicloud.com/community/myblog" target="_blank" rel="noopener noreferrer">华为云开发者社区专家博主</a><br>
  🏅<a href="https://developer.aliyun.com/my?spm=a2c6h.13148508.setting.3.21fc4f0eCmz1v3#/article?_k=zooqoz" target="_blank" rel="noopener noreferrer">阿里云开发者社区专家博主</a><br>
💊<strong>交流社区：</strong><a href="https://bbs.csdn.net/forums/lcy" target="_blank" rel="noopener noreferrer">运维交流社区</a> 欢迎大家的加入！</p>
</blockquote>
<h2 id="具体报错信息" tabindex="-1"><a class="header-anchor" href="#具体报错信息"><span>具体报错信息：</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# docker pull mysql:5.7.38</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Trying</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> repository</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/library/mysql</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ...</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://registry-1.docker.io/v2/:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> x509:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> certificate</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> has</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> expired</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> or</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> not</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> yet</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> valid</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>发现报错</p>
<blockquote>
<font color=red>x509: certificate has expired or is not yet valid</font> 翻译过来就是 <font color=green>x509：证书已过期或尚未生效</font></blockquote>
<h2 id="问题排查" tabindex="-1"><a class="header-anchor" href="#问题排查"><span>问题排查：</span></a></h2>
<h3 id="时间问题排查" tabindex="-1"><a class="header-anchor" href="#时间问题排查"><span>时间问题排查</span></a></h3>
<p>首先我们先看时间问题；<br>
在docker拉取镜像时出现 x509 报错,一般都是证书问题或者系统时间问题导致，可以先执行 ​​date​​ 看一下系统时间对不对,如果服务器系统时间跟现实实际时间对不上的话，一般就是系统时间问题，同步时间即可。</p>
<h4 id="_1-查看时间" tabindex="-1"><a class="header-anchor" href="#_1-查看时间"><span>1 查看时间</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# date</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2023年</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 02月</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17日</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 星期五</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 06:09:59</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> CST</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>确定系统时间与现在的时间对不上，估计就是这个问题了，我们来同步一下时间。</p>
<h4 id="_2-安装同步时间工具-ntpdate" tabindex="-1"><a class="header-anchor" href="#_2-安装同步时间工具-ntpdate"><span>2 安装同步时间工具 ntpdate</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">yum</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -y</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ntpdate</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="_3-同步时间" tabindex="-1"><a class="header-anchor" href="#_3-同步时间"><span>3 同步时间</span></a></h4>
<p>安装完命令之后同步时间；</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# ntpdate cn.pool.ntp.org</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> 7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Mar</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 10:40:40</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ntpdate[6276]:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> step</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> time</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 120.25.115.20</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> offset</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1571423.500135</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sec</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>同步完成之后再次查看一下时间</p>
<h4 id="_4-再次查看当前系统时间" tabindex="-1"><a class="header-anchor" href="#_4-再次查看当前系统时间"><span>4 再次查看当前系统时间</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# date</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">2023年</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 03月</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 07日</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 星期二</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 10:40:43</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> CST</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>同步成功，再次拉取镜像试一下</p>
<h4 id="_5-再次拉取镜像" tabindex="-1"><a class="header-anchor" href="#_5-再次拉取镜像"><span>5 再次拉取镜像</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# docker pull mysql:5.7.38</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Trying</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> repository</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/library/mysql</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ...</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">5.7.38:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pulling</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/library/mysql</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">66fb34780033:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ef4ccd63cdb4:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d6f28a94c51f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">7feea2a503b5:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">71dd5852ecd9:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">3da2c95cac2f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">af7913db289c:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">77f552f93c12:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">3ed53edb61ab:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">67e1c6839f08:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">abcdaaf08d0f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Digest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sha256:bbe0e2b0a33ef5c3a983e490dcb3c1a42d623db1d5679e82f65cce3f32c8f254</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Status:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloaded</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> newer</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> image</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/mysql:5.7.38</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>发现没有报错，拉取成功，问题解决。</p>
<p>如果还是有报错看第二种方法：</p>
<h3 id="证书问题排查" tabindex="-1"><a class="header-anchor" href="#证书问题排查"><span>证书问题排查</span></a></h3>
<p>证书问题需要编辑 <font color=red>​​/etc/docker/daemon.json</font> 文件，在配置文件中添加 <font color=red>​​​​&quot;registry-mirrors&quot;:[&quot;<a href="https://docker.mirrors.ustc.edu.cn" target="_blank" rel="noopener noreferrer">https://docker.mirrors.ustc.edu.cn</a>&quot;]​​</font> 配置。</p>
<h4 id="编辑-etc-docker-daemon-json文件" tabindex="-1"><a class="header-anchor" href="#编辑-etc-docker-daemon-json文件"><span>编辑/etc/docker/daemon.json文件</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# vim /etc/docker/daemon.json</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">{</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"registry-mirrors"</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">[</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"https://hx983jf6.mirror.aliyuncs.com"</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">,</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"https://docker.mirrors.ustc.edu.cn"</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">],</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  //第一个是镜像加速配置</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"graph"</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">:</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"/mnt/data"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    //修改Docker默认存储路径配置</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="更新docker-daemon-json配置" tabindex="-1"><a class="header-anchor" href="#更新docker-daemon-json配置"><span>更新docker/daemon.json配置</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">systemctl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> daemon-reload</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="重启docker服务" tabindex="-1"><a class="header-anchor" href="#重启docker服务"><span>重启docker服务</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">systemctl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> restart</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="再次拉取镜像" tabindex="-1"><a class="header-anchor" href="#再次拉取镜像"><span>再次拉取镜像</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8d mysql]# docker pull mysql:5.7.38</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Trying</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> repository</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/library/mysql</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ...</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">5.7.38:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pulling</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/library/mysql</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">66fb34780033:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ef4ccd63cdb4:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">d6f28a94c51f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">7feea2a503b5:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">71dd5852ecd9:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">3da2c95cac2f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">af7913db289c:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">77f552f93c12:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">3ed53edb61ab:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">67e1c6839f08:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">abcdaaf08d0f:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Pull</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> complete</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Digest:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sha256:bbe0e2b0a33ef5c3a983e490dcb3c1a42d623db1d5679e82f65cce3f32c8f254</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Status:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Downloaded</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> newer</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> image</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> docker.io/mysql:5.7.38</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>发现没有报错，拉取成功，问题解决。</p>
<h2 id="成功解决" tabindex="-1"><a class="header-anchor" href="#成功解决"><span>成功解决</span></a></h2>
</div></template>


