<template><div><blockquote>
<p>👨‍🎓<strong>博主简介</strong></p>
<p>  🏅<a href="https://blog.csdn.net/liu_chen_yang?type=blog" target="_blank" rel="noopener noreferrer">云计算领域优质创作者</a><br>
  🏅<a href="https://bbs.huaweicloud.com/community/myblog" target="_blank" rel="noopener noreferrer">华为云开发者社区专家博主</a><br>
  🏅<a href="https://developer.aliyun.com/my?spm=a2c6h.13148508.setting.3.21fc4f0eCmz1v3#/article?_k=zooqoz" target="_blank" rel="noopener noreferrer">阿里云开发者社区专家博主</a><br>
💊<strong>交流社区：</strong><a href="https://bbs.csdn.net/forums/lcy" target="_blank" rel="noopener noreferrer">运维交流社区</a> 欢迎大家的加入！<br>
🐋 希望大家多多支持，我们一起进步！😄<br>
🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗</p>
</blockquote>
<hr>
<h2 id="报错数据" tabindex="-1"><a class="header-anchor" href="#报错数据"><span>报错数据</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8s-master ~]# useradd 123123</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">useradd:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> invalid</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '123123'</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="报错原因" tabindex="-1"><a class="header-anchor" href="#报错原因"><span>报错原因</span></a></h2>
<blockquote>
<p>是因为linux系统用户的uid就是纯数字，所以被限制不能创建纯数字用户名</p>
</blockquote>
<h2 id="解决思路" tabindex="-1"><a class="header-anchor" href="#解决思路"><span>解决思路</span></a></h2>
<p>其实想了一下，有这样的限制也是有道理的，毕竟linux系统用户的uid就是纯数字的</p>
<p>比如像id 之类的命令，是可以直接指定uid或者用户名的，如果是纯数字了，到底应该视为什么呢？</p>
<p>不过测试过，冲突了还是只显示用户名为纯数字的用户信息，总之只会显示一个用户的信息</p>
<p>查询了redhat相关的文档，其中redhat 7.6 版本的Release_Notes已经说明了,如下:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">All-numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> shadow-utils</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> are</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> now</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> deprecated</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Creating</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> consisting</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> purely</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> characters</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> using</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> useradd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">groupadd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> commands</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> now</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> deprecated</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> will</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> be</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> removed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> system</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> next</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> major</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">release.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Such</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> can</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> potentially</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> confuse</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> many</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tools</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> that</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> work</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ids</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (which </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">are</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> numbers</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">).</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也就是说，从<code v-pre>7.6版本</code>开始弃用创建纯数字的用户名；<br>
但是<code v-pre>7.6--7.9版本</code>之间可以使用环境变量来创建的；<br>
但是从<code v-pre>8版本</code>会直接删除那种使用命令创建纯数字用户名的方式，使用环境变量也不能来创建。</p>
<p>后来在Red Hat Bugzilla – Bug 1672958 文档中也发现了此解释,如下</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> useradd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> groupadd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> commands</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disallow</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">consisting</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> purely</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> characters</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> since</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Red</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Hat</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Enterprise</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Linux</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 7.6.</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reason</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> for</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> not</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> allowing</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> such</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> that</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> this</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> can</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> confuse</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> potentially</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">many</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> tools</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> that</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> work</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ids</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">which</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> are</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> numbers</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> However</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> due</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> some</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> deployments</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> depending</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> on</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> allowing</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> all-numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">this</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> erratum</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> makes</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> useradd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> groupadd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> commands</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> allow</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> all-numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">if</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> environment</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> variable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> SHADOW_ALLOW_ALL_NUMERIC_USER</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set.</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Please</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> note</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> that</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> all-numeric</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> group</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> names</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> are</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">deprecated</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Red</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Hat</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Enterprise</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Linux</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 7</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> and</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> support</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> will</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> be</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> completely</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> removed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Red</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Hat</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Enterprise</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Linux</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 8.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="解决方法-适用于centos-7-6-7-9" tabindex="-1"><a class="header-anchor" href="#解决方法-适用于centos-7-6-7-9"><span>解决方法（适用于centos 7.6-7.9）</span></a></h2>
<p>但是终究还是有方法改变这个限制的，可以使用export定义SHADOW_ALLOW_ALL_NUMERIC_USER变量的值为1，如下：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-dark:#7F848E;--shiki-light-font-style:italic;--shiki-dark-font-style:italic">#设置临时环境变量</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">export</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> SHADOW_ALLOW_ALL_NUMERIC_USER</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-dark:#7F848E;--shiki-light-font-style:italic;--shiki-dark-font-style:italic">#创建纯数字用户</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">useradd</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 123123</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">useradd</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -g</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> test</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /sbin/nologin</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 123123</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-dark:#7F848E;--shiki-light-font-style:italic;--shiki-dark-font-style:italic">#查看最后3个用户</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tail</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -n</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /etc/passwd</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>设置永久生效</li>
</ul>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">echo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "export SHADOW_ALLOW_ALL_NUMERIC_USER=1"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> >> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">/root/.bashrc</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这样，每次连接该ip的时候都会自动生效了。</p>
</div></template>


