export const data = JSON.parse("{\"key\":\"v-176fb820\",\"path\":\"/cloud/Docker/linux%EF%BC%88centos%EF%BC%89%E4%B8%AD%E9%83%A8%E7%BD%B2docker%EF%BC%88%E6%AD%A5%E9%AA%A4%E8%B6%85%E5%85%A8%EF%BC%8C%E5%90%AB%E5%B8%A6%E4%B8%80%E4%BA%9B%E5%8F%91%E5%B1%95%E5%8F%B2%E5%92%8C%E4%B8%80%E4%BA%9B%E6%A6%82%E5%BF%B5%EF%BC%89.html\",\"title\":\"前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] &emsp;&emsp;Docker 是一个开源的应用容器引擎，基于Go语言 并遵从 Apache2.0 协议开源。 &emsp;&emsp;Docker 可以让开发者打包他们的应用以及依赖包到一个轻量级、可移植的容器中，然后发布到任何流行的 Linux 机器上，也可以实现虚拟化。容器是完全使用沙箱机制，相互之间不会有任何接口,更重要的是容...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Docker/linux%EF%BC%88centos%EF%BC%89%E4%B8%AD%E9%83%A8%E7%BD%B2docker%EF%BC%88%E6%AD%A5%E9%AA%A4%E8%B6%85%E5%85%A8%EF%BC%8C%E5%90%AB%E5%B8%A6%E4%B8%80%E4%BA%9B%E5%8F%91%E5%B1%95%E5%8F%B2%E5%92%8C%E4%B8%80%E4%BA%9B%E6%A6%82%E5%BF%B5%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] &emsp;&emsp;Docker 是一个开源的应用容器引擎，基于Go语言 并遵从 Apache2.0 协议开源。 &emsp;&emsp;Docker 可以让开发者打包他们的应用以及依赖包到一个轻量级、可移植的容器中，然后发布到任何流行的 Linux 机器上，也可以实现虚拟化。容器是完全使用沙箱机制，相互之间不会有任何接口,更重要的是容...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"docker安装\",\"slug\":\"docker安装\",\"link\":\"#docker安装\",\"children\":[{\"level\":3,\"title\":\"离线安装\",\"slug\":\"离线安装\",\"link\":\"#离线安装\",\"children\":[]},{\"level\":3,\"title\":\"在线安装\",\"slug\":\"在线安装\",\"link\":\"#在线安装\",\"children\":[]}]},{\"level\":2,\"title\":\"docker镜像管理\",\"slug\":\"docker镜像管理\",\"link\":\"#docker镜像管理\",\"children\":[]},{\"level\":2,\"title\":\"docker容器管理\",\"slug\":\"docker容器管理\",\"link\":\"#docker容器管理\",\"children\":[]},{\"level\":2,\"title\":\"docker运行容器命令\",\"slug\":\"docker运行容器命令\",\"link\":\"#docker运行容器命令\",\"children\":[]}],\"readingTime\":{\"minutes\":13.84,\"words\":4151},\"filePathRelative\":\"cloud/Docker/linux（centos）中部署docker（步骤超全，含带一些发展史和一些概念）.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
