export const data = JSON.parse("{\"key\":\"v-2cd20002\",\"path\":\"/cloud/Docker/Linux%E4%B8%AD%E5%AE%89%E8%A3%85_%E9%83%A8%E7%BD%B2docker-compose.html\",\"title\":\"前提\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] 必须要有docker，如果没有可以去查看：linux（centos）中部署docker（步骤超全，含带一些发展史和一些概念） (https://blog.csdn.net/liuchenyang/article/details/123842609)，有安装步骤。 在这里插入图片描述 在这里插入图片描述 第一种：按照官方文档下载docker-...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Docker/Linux%E4%B8%AD%E5%AE%89%E8%A3%85_%E9%83%A8%E7%BD%B2docker-compose.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前提\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] 必须要有docker，如果没有可以去查看：linux（centos）中部署docker（步骤超全，含带一些发展史和一些概念） (https://blog.csdn.net/liuchenyang/article/details/123842609)，有安装步骤。 在这里插入图片描述 在这里插入图片描述 第一种：按照官方文档下载docker-...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前提\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"第一种：按照官方文档下载docker-compose包来安装\",\"slug\":\"第一种-按照官方文档下载docker-compose包来安装\",\"link\":\"#第一种-按照官方文档下载docker-compose包来安装\",\"children\":[{\"level\":3,\"title\":\"（1）下载docker-compose\",\"slug\":\"_1-下载docker-compose\",\"link\":\"#_1-下载docker-compose\",\"children\":[]},{\"level\":3,\"title\":\"（2）修改目录权限\",\"slug\":\"_2-修改目录权限\",\"link\":\"#_2-修改目录权限\",\"children\":[]},{\"level\":3,\"title\":\"（3）创建软连接\",\"slug\":\"_3-创建软连接\",\"link\":\"#_3-创建软连接\",\"children\":[]},{\"level\":3,\"title\":\"（4）验证安装是否完成\",\"slug\":\"_4-验证安装是否完成\",\"link\":\"#_4-验证安装是否完成\",\"children\":[]}]},{\"level\":2,\"title\":\"第二种：使用pip install 的方式安装\",\"slug\":\"第二种-使用pip-install-的方式安装\",\"link\":\"#第二种-使用pip-install-的方式安装\",\"children\":[{\"level\":3,\"title\":\"（1）首先需要确保pip已经安装完成，如下\",\"slug\":\"_1-首先需要确保pip已经安装完成-如下\",\"link\":\"#_1-首先需要确保pip已经安装完成-如下\",\"children\":[]},{\"level\":3,\"title\":\"（2）升级pip的版本\",\"slug\":\"_2-升级pip的版本\",\"link\":\"#_2-升级pip的版本\",\"children\":[]},{\"level\":3,\"title\":\"（3）安装docker-compose\",\"slug\":\"_3-安装docker-compose\",\"link\":\"#_3-安装docker-compose\",\"children\":[]},{\"level\":3,\"title\":\"（4）验证是否安装完成\",\"slug\":\"_4-验证是否安装完成\",\"link\":\"#_4-验证是否安装完成\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.6,\"words\":1079},\"filePathRelative\":\"cloud/Docker/Linux中安装_部署docker-compose.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
