export const data = JSON.parse("{\"key\":\"v-6d8a6ccc\",\"path\":\"/cloud/Docker/podman%20%E6%9B%BF%E4%BB%A3%20docker%20%EF%BC%9F%20centos%20Stream%2010%20%E5%B7%B2%E7%BB%8F%E5%BC%83%E7%94%A8docker%EF%BC%8C%E5%BC%80%E5%A7%8B%E7%94%A8podman%E4%BA%86%EF%BC%81.html\",\"title\":\"一、什么是 podman？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅CSDN博客专家 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Docker/podman%20%E6%9B%BF%E4%BB%A3%20docker%20%EF%BC%9F%20centos%20Stream%2010%20%E5%B7%B2%E7%BB%8F%E5%BC%83%E7%94%A8docker%EF%BC%8C%E5%BC%80%E5%A7%8B%E7%94%A8podman%E4%BA%86%EF%BC%81.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一、什么是 podman？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅CSDN博客专家 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一、什么是 podman？\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1、podman 镜像管理\",\"slug\":\"_1、podman-镜像管理\",\"link\":\"#_1、podman-镜像管理\",\"children\":[]},{\"level\":2,\"title\":\"2、podman容器管理\",\"slug\":\"_2、podman容器管理\",\"link\":\"#_2、podman容器管理\",\"children\":[]},{\"level\":2,\"title\":\"3、podman运行容器命令\",\"slug\":\"_3、podman运行容器命令\",\"link\":\"#_3、podman运行容器命令\",\"children\":[]},{\"level\":2,\"title\":\"1、podman 中没有数据修改存储路径\",\"slug\":\"_1、podman-中没有数据修改存储路径\",\"link\":\"#_1、podman-中没有数据修改存储路径\",\"children\":[]},{\"level\":2,\"title\":\"2、podman 中有数据迁移修改存储路径\",\"slug\":\"_2、podman-中有数据迁移修改存储路径\",\"link\":\"#_2、podman-中有数据迁移修改存储路径\",\"children\":[]}],\"readingTime\":{\"minutes\":9.73,\"words\":2920},\"filePathRelative\":\"cloud/Docker/podman 替代 docker ？ centos Stream 10 已经弃用docker，开始用podman了！.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
