export const data = JSON.parse("{\"key\":\"v-e0004b92\",\"path\":\"/Linux/clamav%E5%8D%87%E7%BA%A7%E9%97%AE%E9%A2%98%E6%8A%A5%E9%94%992%EF%BC%9ACan%E2%80%98t%20query%20current.cvd.clamav.net.html\",\"title\":\"clamav升级问题报错2：Can‘t query current.cvd.clamav.net\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"clamav升级问题报错2：Can‘t query current.cvd.clamav.net\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"clamav\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-19T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/Linux/clamav%E5%8D%87%E7%BA%A7%E9%97%AE%E9%A2%98%E6%8A%A5%E9%94%992%EF%BC%9ACan%E2%80%98t%20query%20current.cvd.clamav.net.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"clamav升级问题报错2：Can‘t query current.cvd.clamav.net\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"clamav\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-19T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"clamav升级问题报错2：Can‘t query current.cvd.clamav.net\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-19T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"freshclam升级报错：\",\"slug\":\"freshclam升级报错\",\"link\":\"#freshclam升级报错\",\"children\":[]},{\"level\":2,\"title\":\"freshclam升级报错原因：\",\"slug\":\"freshclam升级报错原因\",\"link\":\"#freshclam升级报错原因\",\"children\":[]},{\"level\":2,\"title\":\"解决方式：\",\"slug\":\"解决方式\",\"link\":\"#解决方式\",\"children\":[]}],\"readingTime\":{\"minutes\":1.53,\"words\":459},\"filePathRelative\":\"Linux/clamav升级问题报错2：Can‘t query current.cvd.clamav.net.md\",\"localizedDate\":\"2024年12月19日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
