export const data = JSON.parse("{\"key\":\"v-98155202\",\"path\":\"/Linux/%E3%80%90Linux%E3%80%91%E5%88%87%E6%8D%A2%E5%86%85%E6%A0%B8%E7%89%88%E6%9C%AC%EF%BC%88Centos%EF%BC%89.html\",\"title\":\"【Linux】切换内核版本（Centos）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】切换内核版本（Centos）\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-18T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/Linux/%E3%80%90Linux%E3%80%91%E5%88%87%E6%8D%A2%E5%86%85%E6%A0%B8%E7%89%88%E6%9C%AC%EF%BC%88Centos%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Linux】切换内核版本（Centos）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-18T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Linux】切换内核版本（Centos）\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-18T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.查看服务器已安装的所有内核版本\",\"slug\":\"_1-查看服务器已安装的所有内核版本\",\"link\":\"#_1-查看服务器已安装的所有内核版本\",\"children\":[]},{\"level\":2,\"title\":\"2.修改版本配置\",\"slug\":\"_2-修改版本配置\",\"link\":\"#_2-修改版本配置\",\"children\":[]},{\"level\":2,\"title\":\"3.编译配置\",\"slug\":\"_3-编译配置\",\"link\":\"#_3-编译配置\",\"children\":[]},{\"level\":2,\"title\":\"4.重启系统\",\"slug\":\"_4-重启系统\",\"link\":\"#_4-重启系统\",\"children\":[]},{\"level\":2,\"title\":\"5.重启后查看内核版本\",\"slug\":\"_5-重启后查看内核版本\",\"link\":\"#_5-重启后查看内核版本\",\"children\":[]}],\"readingTime\":{\"minutes\":1.29,\"words\":387},\"filePathRelative\":\"Linux/【Linux】切换内核版本（Centos）.md\",\"localizedDate\":\"2024年12月18日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
