export const data = JSON.parse("{\"key\":\"v-7df88dc8\",\"path\":\"/middleware/docker/custom-network.html\",\"title\":\"自定义网络\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"自定义网络\",\"icon\":\"circle-info\",\"order\":7,\"tag\":[\"docker🛥️\"],\"category\":[\"docker🛥️\"],\"pageview\":false,\"date\":\"2023-12-13T15:21:31.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"1.前言 大家好，我是Leo哥🫣🫣🫣。前面我们创建了一个Java项目的容器，而Java项目往往需要访问其它各种中间件，例如MySQL、Redis等。现在，我们的容器之间能否互相访问呢？我们这篇文章主要讨论如何在Docker中使用网络。 2.测试访问 首先，我们查看下MySQL容器的详细信息，重点关注其中的网络IP地址： ```Bash docke...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/middleware/docker/custom-network.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"自定义网络\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1.前言 大家好，我是Leo哥🫣🫣🫣。前面我们创建了一个Java项目的容器，而Java项目往往需要访问其它各种中间件，例如MySQL、Redis等。现在，我们的容器之间能否互相访问呢？我们这篇文章主要讨论如何在Docker中使用网络。 2.测试访问 首先，我们查看下MySQL容器的详细信息，重点关注其中的网络IP地址： ```Bash docke...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"docker🛥️\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-12-13T15:21:31.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"自定义网络\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-12-13T15:21:31.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2.测试访问\",\"slug\":\"_2-测试访问\",\"link\":\"#_2-测试访问\",\"children\":[]},{\"level\":2,\"title\":\"3.常见命令\",\"slug\":\"_3-常见命令\",\"link\":\"#_3-常见命令\",\"children\":[]},{\"level\":2,\"title\":\"4.自定义网络\",\"slug\":\"_4-自定义网络\",\"link\":\"#_4-自定义网络\",\"children\":[]},{\"level\":2,\"title\":\"5.总结\",\"slug\":\"_5-总结\",\"link\":\"#_5-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.2,\"words\":1260},\"filePathRelative\":\"middleware/docker/custom-network.md\",\"localizedDate\":\"2023年12月13日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
