export const data = JSON.parse("{\"key\":\"v-baf8b422\",\"path\":\"/middleware/docker/docker-make-mirror-image.html\",\"title\":\"使用Dockerfile制作镜像\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"使用Dockerfile制作镜像\",\"icon\":\"circle-info\",\"order\":8,\"tag\":[\"docker🛥️\"],\"category\":[\"docker🛥️\"],\"pageview\":false,\"date\":\"2023-12-13T15:21:31.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"1.前言 大家好，我是Leo哥🫣🫣🫣，这篇文章 (https://gaoziman.blog.csdn.net/article/details/134671157)中，我们学习了什么是镜像，以及如何自定义镜像。这篇文章我们主要讲一下如果使用Dockerfile快速制作镜像、好了，话不多说让我们开始吧😎😎😎。 2.细节注意 我们打包镜像也是分...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/middleware/docker/docker-make-mirror-image.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"使用Dockerfile制作镜像\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1.前言 大家好，我是Leo哥🫣🫣🫣，这篇文章 (https://gaoziman.blog.csdn.net/article/details/134671157)中，我们学习了什么是镜像，以及如何自定义镜像。这篇文章我们主要讲一下如果使用Dockerfile快速制作镜像、好了，话不多说让我们开始吧😎😎😎。 2.细节注意 我们打包镜像也是分...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"docker🛥️\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-12-13T15:21:31.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"使用Dockerfile制作镜像\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-12-13T15:21:31.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2.细节注意\",\"slug\":\"_2-细节注意\",\"link\":\"#_2-细节注意\",\"children\":[]},{\"level\":2,\"title\":\"3.Dockefile\",\"slug\":\"_3-dockefile\",\"link\":\"#_3-dockefile\",\"children\":[]},{\"level\":2,\"title\":\"3.构建镜像\",\"slug\":\"_3-构建镜像\",\"link\":\"#_3-构建镜像\",\"children\":[]},{\"level\":2,\"title\":\"4.总结\",\"slug\":\"_4-总结\",\"link\":\"#_4-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.85,\"words\":1456},\"filePathRelative\":\"middleware/docker/docker-make-mirror-image.md\",\"localizedDate\":\"2023年12月13日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
