import comp from "D:/JAVA项目/new_cs/rc67/src/.vuepress/.temp/pages/document/Linux/Linux设置永久别名alias的方法.html.vue"
const data = JSON.parse("{\"path\":\"/document/Linux/Linux%E8%AE%BE%E7%BD%AE%E6%B0%B8%E4%B9%85%E5%88%AB%E5%90%8Dalias%E7%9A%84%E6%96%B9%E6%B3%95.html\",\"title\":\"Linux设置永久别名alias的方法\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Linux设置永久别名alias的方法\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-19T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"gitInclude\":[],\"description\":\"编辑文件，该文件主要用于保存一些个性化的设置，如命令别名、路径等： 进入该文件里，我们要在最后一行或者最后在空出来几行来新增我们的个性化配置，如设置别名： 比如下图👇 设置完之后，我们:wq保存并退出 :wq 保存文件后，在执行命令，使之生效。 然后自己可以去测试一下； 最后，需要我们注意的是，.bashrc文件是针对用户级别的个性化设置。切记切记！...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/document/Linux/Linux%E8%AE%BE%E7%BD%AE%E6%B0%B8%E4%B9%85%E5%88%AB%E5%90%8Dalias%E7%9A%84%E6%96%B9%E6%B3%95.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Linux设置永久别名alias的方法\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"编辑文件，该文件主要用于保存一些个性化的设置，如命令别名、路径等： 进入该文件里，我们要在最后一行或者最后在空出来几行来新增我们的个性化配置，如设置别名： 比如下图👇 设置完之后，我们:wq保存并退出 :wq 保存文件后，在执行命令，使之生效。 然后自己可以去测试一下； 最后，需要我们注意的是，.bashrc文件是针对用户级别的个性化设置。切记切记！...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412191616331.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-19T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Linux设置永久别名alias的方法\\\",\\\"image\\\":[\\\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412191616331.png\\\",\\\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412191616470.png\\\"],\\\"datePublished\\\":\\\"2024-12-19T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.76,\"words\":228},\"filePathRelative\":\"document/Linux/Linux设置永久别名alias的方法.md\",\"localizedDate\":\"2024年12月19日\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
