import comp from "D:/JAVA项目/new_cs/rc67/src/.vuepress/.temp/pages/document/Linux/【Linux】grep -q用法详解.html.vue"
const data = JSON.parse("{\"path\":\"/document/Linux/%E3%80%90Linux%E3%80%91grep%20-q%E7%94%A8%E6%B3%95%E8%AF%A6%E8%A7%A3.html\",\"title\":\"【Linux】grep -q用法详解\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】grep -q用法详解\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-17T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"gitInclude\":[],\"description\":\"👨‍🎓博主简介 🏅云计算领域优质创作者 🏅华为云开发者社区专家博主 🏅阿里云开发者社区专家博主 💊交流社区：运维交流社区 欢迎大家的加入！ 🐋 希望大家多多支持，我们一起进步！😄 🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗 grep -q 简介 用于if逻辑判断 安静模式，不打印任何标准输出。...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/document/Linux/%E3%80%90Linux%E3%80%91grep%20-q%E7%94%A8%E6%B3%95%E8%AF%A6%E8%A7%A3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Linux】grep -q用法详解\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 🏅云计算领域优质创作者 🏅华为云开发者社区专家博主 🏅阿里云开发者社区专家博主 💊交流社区：运维交流社区 欢迎大家的加入！ 🐋 希望大家多多支持，我们一起进步！😄 🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗 grep -q 简介 用于if逻辑判断 安静模式，不打印任何标准输出。...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412171025290.gif\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-17T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Linux】grep -q用法详解\\\",\\\"image\\\":[\\\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412171025290.gif\\\"],\\\"datePublished\\\":\\\"2024-12-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"grep -q 简介\",\"slug\":\"grep-q-简介\",\"link\":\"#grep-q-简介\",\"children\":[]},{\"level\":2,\"title\":\"用法\",\"slug\":\"用法\",\"link\":\"#用法\",\"children\":[]},{\"level\":2,\"title\":\"实例\",\"slug\":\"实例\",\"link\":\"#实例\",\"children\":[{\"level\":3,\"title\":\"实例1\",\"slug\":\"实例1\",\"link\":\"#实例1\",\"children\":[]},{\"level\":3,\"title\":\"实例2\",\"slug\":\"实例2\",\"link\":\"#实例2\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.34,\"words\":402},\"filePathRelative\":\"document/Linux/【Linux】grep -q用法详解.md\",\"localizedDate\":\"2024年12月17日\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
