export const data = JSON.parse("{\"key\":\"v-326619e4\",\"path\":\"/cloud/Docker/yaml%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%AF%A6%E8%A7%A3%E5%8F%8A%E5%AE%9E%E4%BE%8B.html\",\"title\":\"yaml简介\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Docker/yaml%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%AF%A6%E8%A7%A3%E5%8F%8A%E5%AE%9E%E4%BE%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"yaml简介\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"yaml简介\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"数组（列表）实例； 短横线加空格（- ）\",\"slug\":\"数组-列表-实例-短横线加空格\",\"link\":\"#数组-列表-实例-短横线加空格\",\"children\":[]},{\"level\":2,\"title\":\"Yaml 对象（字典）实例；用冒号加空格连接键和值（: ）\",\"slug\":\"yaml-对象-字典-实例-用冒号加空格连接键和值\",\"link\":\"#yaml-对象-字典-实例-用冒号加空格连接键和值\",\"children\":[]},{\"level\":2,\"title\":\"Yaml 数组 对象结合（列表中的字典）实例；短横线加空格（- ），用冒号加空格连接键和值（: ）\",\"slug\":\"yaml-数组-对象结合-列表中的字典-实例-短横线加空格-用冒号加空格连接键和值\",\"link\":\"#yaml-数组-对象结合-列表中的字典-实例-短横线加空格-用冒号加空格连接键和值\",\"children\":[]},{\"level\":2,\"title\":\"格式说明\",\"slug\":\"格式说明\",\"link\":\"#格式说明\",\"children\":[]},{\"level\":2,\"title\":\"实例\",\"slug\":\"实例\",\"link\":\"#实例\",\"children\":[]}],\"readingTime\":{\"minutes\":10.7,\"words\":3210},\"filePathRelative\":\"cloud/Docker/yaml文件格式详解及实例.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
