export const data = JSON.parse("{\"key\":\"v-6a7d5d3b\",\"path\":\"/secure/openssh/.~%E3%80%90Linux%E3%80%91%20OpenSSH_9.3p1%20%E5%8D%87%E7%BA%A7%E5%88%B0%20OpenSSH_9.5p1%EF%BC%88%E4%BA%B2%E6%B5%8B%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%8C%E5%BB%BA%E8%AE%AE%E6%94%B6%E8%97%8F%EF%BC%89.html\",\"title\":\"【Linux】 OpenSSH_9.3p1 升级到 OpenSSH_9.5p1（亲测无问题，建议收藏）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】 OpenSSH_9.3p1 升级到 OpenSSH_9.5p1（亲测无问题，建议收藏）\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\",\"服务器安全\"],\"tag\":[\"Linux\",\"服务器安全\",\"openssh\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-15T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"},\"headers\":[{\"level\":2,\"title\":\"文章声明\",\"slug\":\"文章声明\",\"link\":\"#文章声明\",\"children\":[]},{\"level\":2,\"title\":\"漏洞描述\",\"slug\":\"漏洞描述\",\"link\":\"#漏洞描述\",\"children\":[]},{\"level\":2,\"title\":\"前述\",\"slug\":\"前述\",\"link\":\"#前述\",\"children\":[]},{\"level\":2,\"title\":\"此文升级是基于9.3p1升级9.5p1\",\"slug\":\"此文升级是基于9-3p1升级9-5p1\",\"link\":\"#此文升级是基于9-3p1升级9-5p1\",\"children\":[{\"level\":3,\"title\":\"备份openssh9.3p1的配置文件\",\"slug\":\"备份openssh9-3p1的配置文件\",\"link\":\"#备份openssh9-3p1的配置文件\",\"children\":[]},{\"level\":3,\"title\":\"下载 openssh9.5p1 的安装包：\",\"slug\":\"下载-openssh9-5p1-的安装包\",\"link\":\"#下载-openssh9-5p1-的安装包\",\"children\":[]},{\"level\":3,\"title\":\"解压并编译安装openssh9.5p1\",\"slug\":\"解压并编译安装openssh9-5p1\",\"link\":\"#解压并编译安装openssh9-5p1\",\"children\":[]},{\"level\":3,\"title\":\"授权\",\"slug\":\"授权\",\"link\":\"#授权\",\"children\":[]},{\"level\":3,\"title\":\"复制配置文件\",\"slug\":\"复制配置文件\",\"link\":\"#复制配置文件\",\"children\":[]},{\"level\":3,\"title\":\"给sshd授予权限\",\"slug\":\"给sshd授予权限\",\"link\":\"#给sshd授予权限\",\"children\":[]},{\"level\":3,\"title\":\"启用sshd，生成服务配置文件，并重启服务\",\"slug\":\"启用sshd-生成服务配置文件-并重启服务\",\"link\":\"#启用sshd-生成服务配置文件-并重启服务\",\"children\":[]},{\"level\":3,\"title\":\"验证升级是否成功\",\"slug\":\"验证升级是否成功\",\"link\":\"#验证升级是否成功\",\"children\":[]}]},{\"level\":2,\"title\":\"相关专栏\",\"slug\":\"相关专栏\",\"link\":\"#相关专栏\",\"children\":[]},{\"level\":2,\"title\":\"相关文章\",\"slug\":\"相关文章\",\"link\":\"#相关文章\",\"children\":[]}],\"readingTime\":{\"minutes\":5.23,\"words\":1570},\"filePathRelative\":\"secure/openssh/.~【Linux】 OpenSSH_9.3p1 升级到 OpenSSH_9.5p1（亲测无问题，建议收藏）.md\",\"localizedDate\":\"2024年12月15日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
