export const data = JSON.parse("{\"key\":\"v-3837074e\",\"path\":\"/automation/ansible/.~Ansible%E8%87%AA%E5%8A%A8%E5%8C%96%E8%BF%90%E7%BB%B4%EF%BC%88%E5%9B%9B%EF%BC%89jinja2%20%E6%A8%A1%E6%9D%BF%E3%80%81Roles%E8%A7%92%E8%89%B2%E8%AF%A6%E8%A7%A3.html\",\"title\":\"Ansible自动化运维（四）jinja2 模板、Roles角色详解\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Ansible自动化运维（四）jinja2 模板、Roles角色详解\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\",\"自动化\",\"Ansible\"],\"tag\":[\"Linux\",\"自动化\",\"Ansible\"],\"pageview\":false,\"date\":\"2024-12-15T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"},\"headers\":[{\"level\":2,\"title\":\"一、jinjia2 模板\",\"slug\":\"一、jinjia2-模板\",\"link\":\"#一、jinjia2-模板\",\"children\":[{\"level\":3,\"title\":\"1.1 在 Ansible 中的使用\",\"slug\":\"_1-1-在-ansible-中的使用\",\"link\":\"#_1-1-在-ansible-中的使用\",\"children\":[]},{\"level\":3,\"title\":\"1.2 jinjia2 模板语法\",\"slug\":\"_1-2-jinjia2-模板语法\",\"link\":\"#_1-2-jinjia2-模板语法\",\"children\":[]},{\"level\":3,\"title\":\"1.3 templates 模块\",\"slug\":\"_1-3-templates-模块\",\"link\":\"#_1-3-templates-模块\",\"children\":[]},{\"level\":3,\"title\":\"1.4 jinja2 使用案例\",\"slug\":\"_1-4-jinja2-使用案例\",\"link\":\"#_1-4-jinja2-使用案例\",\"children\":[]}]},{\"level\":2,\"title\":\"二、Roles 角色\",\"slug\":\"二、roles-角色\",\"link\":\"#二、roles-角色\",\"children\":[{\"level\":3,\"title\":\"2.1 Roles介绍与优势\",\"slug\":\"_2-1-roles介绍与优势\",\"link\":\"#_2-1-roles介绍与优势\",\"children\":[]},{\"level\":3,\"title\":\"2.2 Roles 的目录结构\",\"slug\":\"_2-2-roles-的目录结构\",\"link\":\"#_2-2-roles-的目录结构\",\"children\":[]},{\"level\":3,\"title\":\"2.3 ansible-galaxy 命令\",\"slug\":\"_2-3-ansible-galaxy-命令\",\"link\":\"#_2-3-ansible-galaxy-命令\",\"children\":[]},{\"level\":3,\"title\":\"2.4 使用Roles（部署nginx）\",\"slug\":\"_2-4-使用roles-部署nginx\",\"link\":\"#_2-4-使用roles-部署nginx\",\"children\":[]},{\"level\":3,\"title\":\"2.5 查看 nginx 树形目录结构\",\"slug\":\"_2-5-查看-nginx-树形目录结构\",\"link\":\"#_2-5-查看-nginx-树形目录结构\",\"children\":[]}]},{\"level\":2,\"title\":\"三、相关文章\",\"slug\":\"三、相关文章\",\"link\":\"#三、相关文章\",\"children\":[]}],\"readingTime\":{\"minutes\":15.06,\"words\":4518},\"filePathRelative\":\"automation/ansible/.~Ansible自动化运维（四）jinja2 模板、Roles角色详解.md\",\"localizedDate\":\"2024年12月15日\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
