export const data = JSON.parse("{\"key\":\"v-1383fc04\",\"path\":\"/Linux/Centos7%20gcc4.8.5%E5%8D%87%E7%BA%A7%E5%88%B0%E7%89%88%E6%9C%ACgcc5.4.0%E3%80%90%E5%85%B6%E4%BB%96%E7%89%88%E6%9C%AC%E9%80%9A%E7%94%A8%E3%80%91.html\",\"title\":\"前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] &emsp;&emsp;因为Centos7默认的是gcc4.8.5，但是有时候要用到gcc5.4，因为，我来教大家如何从gcc4.8.5升到到gcc5.4.0。 &emsp;&emsp;如果遇到没有网络的情况下，想要安装gcc，只需要一个安装包，就可以安装； 详细请看：👉Linux中gcc4.8.5升级到gcc5.4.0用已经编译好的安装...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/Linux/Centos7%20gcc4.8.5%E5%8D%87%E7%BA%A7%E5%88%B0%E7%89%88%E6%9C%ACgcc5.4.0%E3%80%90%E5%85%B6%E4%BB%96%E7%89%88%E6%9C%AC%E9%80%9A%E7%94%A8%E3%80%91.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] &emsp;&emsp;因为Centos7默认的是gcc4.8.5，但是有时候要用到gcc5.4，因为，我来教大家如何从gcc4.8.5升到到gcc5.4.0。 &emsp;&emsp;如果遇到没有网络的情况下，想要安装gcc，只需要一个安装包，就可以安装； 详细请看：👉Linux中gcc4.8.5升级到gcc5.4.0用已经编译好的安装...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"安装gcc c++\",\"slug\":\"安装gcc-c\",\"link\":\"#安装gcc-c\",\"children\":[]},{\"level\":2,\"title\":\"安装bzip2\",\"slug\":\"安装bzip2\",\"link\":\"#安装bzip2\",\"children\":[]},{\"level\":2,\"title\":\"下载、解压安装包\",\"slug\":\"下载、解压安装包\",\"link\":\"#下载、解压安装包\",\"children\":[{\"level\":3,\"title\":\"安装包下载地址：\",\"slug\":\"安装包下载地址\",\"link\":\"#安装包下载地址\",\"children\":[]},{\"level\":3,\"title\":\"linux中下载：\",\"slug\":\"linux中下载\",\"link\":\"#linux中下载\",\"children\":[]},{\"level\":3,\"title\":\"解压安装包：\",\"slug\":\"解压安装包\",\"link\":\"#解压安装包\",\"children\":[]}]},{\"level\":2,\"title\":\"下载相关的依赖和组件\",\"slug\":\"下载相关的依赖和组件\",\"link\":\"#下载相关的依赖和组件\",\"children\":[]},{\"level\":2,\"title\":\"新建一个文件夹存放编译的文件\",\"slug\":\"新建一个文件夹存放编译的文件\",\"link\":\"#新建一个文件夹存放编译的文件\",\"children\":[]},{\"level\":2,\"title\":\"编译、安装\",\"slug\":\"编译、安装\",\"link\":\"#编译、安装\",\"children\":[]},{\"level\":2,\"title\":\"查看是否安装成功\",\"slug\":\"查看是否安装成功\",\"link\":\"#查看是否安装成功\",\"children\":[]}],\"readingTime\":{\"minutes\":3.6,\"words\":1081},\"filePathRelative\":\"Linux/Centos7 gcc4.8.5升级到版本gcc5.4.0【其他版本通用】.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
