export const data = JSON.parse("{\"key\":\"v-014be8ea\",\"path\":\"/Linux/%E3%80%90Linux%E3%80%91grep%20-q%E7%94%A8%E6%B3%95%E8%AF%A6%E8%A7%A3.html\",\"title\":\"【Linux】grep -q用法详解\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】grep -q用法详解\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-17T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/Linux/%E3%80%90Linux%E3%80%91grep%20-q%E7%94%A8%E6%B3%95%E8%AF%A6%E8%A7%A3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Linux】grep -q用法详解\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-17T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Linux】grep -q用法详解\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"grep -q 简介\",\"slug\":\"grep-q-简介\",\"link\":\"#grep-q-简介\",\"children\":[]},{\"level\":2,\"title\":\"用法\",\"slug\":\"用法\",\"link\":\"#用法\",\"children\":[]},{\"level\":2,\"title\":\"实例\",\"slug\":\"实例\",\"link\":\"#实例\",\"children\":[{\"level\":3,\"title\":\"实例1\",\"slug\":\"实例1\",\"link\":\"#实例1\",\"children\":[]},{\"level\":3,\"title\":\"实例2\",\"slug\":\"实例2\",\"link\":\"#实例2\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.34,\"words\":402},\"filePathRelative\":\"Linux/【Linux】grep -q用法详解.md\",\"localizedDate\":\"2024年12月17日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
