export const data = JSON.parse("{\"key\":\"v-333e4c11\",\"path\":\"/Linux/%E3%80%90Linux%E3%80%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E9%83%A8%E7%BD%B2Nginx%E6%9C%8D%E5%8A%A1%20-%20%E4%BA%8C%E8%BF%9B%E5%88%B6%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F.html\",\"title\":\"一、下载安装包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/Linux/%E3%80%90Linux%E3%80%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E9%83%A8%E7%BD%B2Nginx%E6%9C%8D%E5%8A%A1%20-%20%E4%BA%8C%E8%BF%9B%E5%88%B6%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一、下载安装包\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一、下载安装包\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1、安装Nginx服务需要的依赖包\",\"slug\":\"_1、安装nginx服务需要的依赖包\",\"link\":\"#_1、安装nginx服务需要的依赖包\",\"children\":[]},{\"level\":2,\"title\":\"2、上传解压\",\"slug\":\"_2、上传解压\",\"link\":\"#_2、上传解压\",\"children\":[]},{\"level\":2,\"title\":\"3、编译安装nginx服务\",\"slug\":\"_3、编译安装nginx服务\",\"link\":\"#_3、编译安装nginx服务\",\"children\":[]},{\"level\":2,\"title\":\"报错1：./configure: error: C compiler cc is not found\",\"slug\":\"报错1-configure-error-c-compiler-cc-is-not-found\",\"link\":\"#报错1-configure-error-c-compiler-cc-is-not-found\",\"children\":[]},{\"level\":2,\"title\":\"报错2：./configure: error: the HTTP rewrite module requires the PCRE library.\",\"slug\":\"报错2-configure-error-the-http-rewrite-module-requires-the-pcre-library\",\"link\":\"#报错2-configure-error-the-http-rewrite-module-requires-the-pcre-library\",\"children\":[]},{\"level\":2,\"title\":\"问题3：./configure: error: the HTTP gzip module requires the zlib library.\",\"slug\":\"问题3-configure-error-the-http-gzip-module-requires-the-zlib-library\",\"link\":\"#问题3-configure-error-the-http-gzip-module-requires-the-zlib-library\",\"children\":[]}],\"readingTime\":{\"minutes\":3.29,\"words\":986},\"filePathRelative\":\"Linux/【Linux】环境下部署Nginx服务 - 二进制部署方式.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
