export const data = JSON.parse("{\"key\":\"v-9aeeed28\",\"path\":\"/Linux/%E3%80%90Linux%E3%80%91Centos%E5%AE%89%E8%A3%85mvn%E5%91%BD%E4%BB%A4%EF%BC%88maven%EF%BC%89.html\",\"title\":\"【Linux】Centos安装mvn命令（maven）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Linux】Centos安装mvn命令（maven）\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\"],\"tag\":[\"Linux\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-17T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/Linux/%E3%80%90Linux%E3%80%91Centos%E5%AE%89%E8%A3%85mvn%E5%91%BD%E4%BB%A4%EF%BC%88maven%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Linux】Centos安装mvn命令（maven）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-17T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Linux】Centos安装mvn命令（maven）\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、下载maven包\",\"slug\":\"一、下载maven包\",\"link\":\"#一、下载maven包\",\"children\":[{\"level\":3,\"title\":\"方法一：官网下载包\",\"slug\":\"方法一-官网下载包\",\"link\":\"#方法一-官网下载包\",\"children\":[]},{\"level\":3,\"title\":\"方法二：wget直接下载\",\"slug\":\"方法二-wget直接下载\",\"link\":\"#方法二-wget直接下载\",\"children\":[]}]},{\"level\":2,\"title\":\"二、配置环境变量\",\"slug\":\"二、配置环境变量\",\"link\":\"#二、配置环境变量\",\"children\":[]},{\"level\":2,\"title\":\"三、mvn校验\",\"slug\":\"三、mvn校验\",\"link\":\"#三、mvn校验\",\"children\":[]}],\"readingTime\":{\"minutes\":2.21,\"words\":664},\"filePathRelative\":\"Linux/【Linux】Centos安装mvn命令（maven）.md\",\"localizedDate\":\"2024年12月17日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
