export const data = JSON.parse("{\"key\":\"v-a68951ca\",\"path\":\"/cloud/Linux/Linux%E7%B3%BB%E7%BB%9F%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%B8%A6%E5%AE%BD%E5%8F%8A%E7%BD%91%E7%BB%9C%E4%BD%BF%E7%94%A8%E6%83%85%E5%86%B5.html\",\"title\":\"前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] &emsp;&emsp;操作系统： Linux &emsp;&emsp;操作环境： Centos7 &emsp;&emsp;Linux系统中如何查看服务器带宽？本篇文章主要和大家分享一下Linux系统中查看服务器带宽的方法，有需要的朋友可以参考一下。 众多网络相关的命令可查看：【Linux】之【网络】相关的命令及解析[ethtool、nlo...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/Linux%E7%B3%BB%E7%BB%9F%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%B8%A6%E5%AE%BD%E5%8F%8A%E7%BD%91%E7%BB%9C%E4%BD%BF%E7%94%A8%E6%83%85%E5%86%B5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] &emsp;&emsp;操作系统： Linux &emsp;&emsp;操作环境： Centos7 &emsp;&emsp;Linux系统中如何查看服务器带宽？本篇文章主要和大家分享一下Linux系统中查看服务器带宽的方法，有需要的朋友可以参考一下。 众多网络相关的命令可查看：【Linux】之【网络】相关的命令及解析[ethtool、nlo...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、使用speedtest-cli命令查看下载和上传最大流量值\",\"slug\":\"一、使用speedtest-cli命令查看下载和上传最大流量值\",\"link\":\"#一、使用speedtest-cli命令查看下载和上传最大流量值\",\"children\":[]},{\"level\":2,\"title\":\"二、查看网卡、网络的详情\",\"slug\":\"二、查看网卡、网络的详情\",\"link\":\"#二、查看网卡、网络的详情\",\"children\":[{\"level\":3,\"title\":\"1.查看服务器网络端口\",\"slug\":\"_1-查看服务器网络端口\",\"link\":\"#_1-查看服务器网络端口\",\"children\":[]},{\"level\":3,\"title\":\"2.ethtool命令查看宽带大小\",\"slug\":\"_2-ethtool命令查看宽带大小\",\"link\":\"#_2-ethtool命令查看宽带大小\",\"children\":[]}]},{\"level\":2,\"title\":\"三、nload命令实时统计网卡带宽使用率\",\"slug\":\"三、nload命令实时统计网卡带宽使用率\",\"link\":\"#三、nload命令实时统计网卡带宽使用率\",\"children\":[]},{\"level\":2,\"title\":\"四、dstat -n命令实时监测网络的状态\",\"slug\":\"四、dstat-n命令实时监测网络的状态\",\"link\":\"#四、dstat-n命令实时监测网络的状态\",\"children\":[]},{\"level\":2,\"title\":\"相关文章\",\"slug\":\"相关文章\",\"link\":\"#相关文章\",\"children\":[]}],\"readingTime\":{\"minutes\":2.36,\"words\":707},\"filePathRelative\":\"cloud/Linux/Linux系统如何查看服务器带宽及网络使用情况.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
