export const data = JSON.parse("{\"key\":\"v-b928c62a\",\"path\":\"/cloud/Linux/linux%E4%BD%BF%E7%94%A8stress%E5%91%BD%E4%BB%A4%E8%BF%9B%E8%A1%8C%E5%8E%8B%E5%8A%9B%E6%B5%8B%E8%AF%95cpu.html\",\"title\":\"查看系统的压力（负载情况）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/linux%E4%BD%BF%E7%94%A8stress%E5%91%BD%E4%BB%A4%E8%BF%9B%E8%A1%8C%E5%8E%8B%E5%8A%9B%E6%B5%8B%E8%AF%95cpu.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"查看系统的压力（负载情况）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"查看系统的压力（负载情况）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"实践：\",\"slug\":\"实践\",\"link\":\"#实践\",\"children\":[]},{\"level\":2,\"title\":\"Linux查看CPU型号（去重）\",\"slug\":\"linux查看cpu型号-去重\",\"link\":\"#linux查看cpu型号-去重\",\"children\":[]},{\"level\":2,\"title\":\"查看物理cpu个数【多少块cpu】\",\"slug\":\"查看物理cpu个数【多少块cpu】\",\"link\":\"#查看物理cpu个数【多少块cpu】\",\"children\":[]},{\"level\":2,\"title\":\"查看cpu是几核\",\"slug\":\"查看cpu是几核\",\"link\":\"#查看cpu是几核\",\"children\":[]},{\"level\":2,\"title\":\"查看逻辑cpu的个数【线程】\",\"slug\":\"查看逻辑cpu的个数【线程】\",\"link\":\"#查看逻辑cpu的个数【线程】\",\"children\":[]}],\"readingTime\":{\"minutes\":4.26,\"words\":1277},\"filePathRelative\":\"cloud/Linux/linux使用stress命令进行压力测试cpu.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
