export const data = JSON.parse("{\"key\":\"v-3cb84392\",\"path\":\"/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%83%A8%E7%BD%B2mailx%E6%9C%8D%E5%8A%A1%E5%8F%8A%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6%E5%91%8A%E8%AD%A6.html\",\"title\":\"一、关闭防火墙或开启53、 25、109、110、143、465、995、993端口\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%83%A8%E7%BD%B2mailx%E6%9C%8D%E5%8A%A1%E5%8F%8A%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6%E5%91%8A%E8%AD%A6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一、关闭防火墙或开启53、 25、109、110、143、465、995、993端口\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一、关闭防火墙或开启53、 25、109、110、143、465、995、993端口\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1、关闭防火墙\",\"slug\":\"_1、关闭防火墙\",\"link\":\"#_1、关闭防火墙\",\"children\":[]},{\"level\":2,\"title\":\"2、开启53、 25、109、110、143、465、995、993端口\",\"slug\":\"_2、开启53、-25、109、110、143、465、995、993端口\",\"link\":\"#_2、开启53、-25、109、110、143、465、995、993端口\",\"children\":[]},{\"level\":2,\"title\":\"3、邮件端口解析\",\"slug\":\"_3、邮件端口解析\",\"link\":\"#_3、邮件端口解析\",\"children\":[]},{\"level\":2,\"title\":\"1、生成授权码\",\"slug\":\"_1、生成授权码\",\"link\":\"#_1、生成授权码\",\"children\":[]},{\"level\":2,\"title\":\"2、编辑配置文件\",\"slug\":\"_2、编辑配置文件\",\"link\":\"#_2、编辑配置文件\",\"children\":[]},{\"level\":2,\"title\":\"使用管道符直接发送\",\"slug\":\"使用管道符直接发送\",\"link\":\"#使用管道符直接发送\",\"children\":[]},{\"level\":2,\"title\":\"发送时显示详细信息\",\"slug\":\"发送时显示详细信息\",\"link\":\"#发送时显示详细信息\",\"children\":[]},{\"level\":2,\"title\":\"带附件发送（即文本或目录）\",\"slug\":\"带附件发送-即文本或目录\",\"link\":\"#带附件发送-即文本或目录\",\"children\":[]}],\"readingTime\":{\"minutes\":8.17,\"words\":2451},\"filePathRelative\":\"cloud/Linux/【Linux】部署mailx服务及发送邮件告警.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
