export const data = JSON.parse("{\"key\":\"v-4b7ae59d\",\"path\":\"/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%83%A8%E7%BD%B2NFS%E6%9C%8D%E5%8A%A1%E5%AE%9E%E7%8E%B0%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB.html\",\"title\":\"一、NFS简介与RPC简介\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅CSDN博客专家 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%83%A8%E7%BD%B2NFS%E6%9C%8D%E5%8A%A1%E5%AE%9E%E7%8E%B0%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一、NFS简介与RPC简介\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅CSDN博客专家 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一、NFS简介与RPC简介\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1. NFS服务简介\",\"slug\":\"_1-nfs服务简介\",\"link\":\"#_1-nfs服务简介\",\"children\":[]},{\"level\":2,\"title\":\"2. RPC协议简介\",\"slug\":\"_2-rpc协议简介\",\"link\":\"#_2-rpc协议简介\",\"children\":[]},{\"level\":2,\"title\":\"3. NFS工作流程\",\"slug\":\"_3-nfs工作流程\",\"link\":\"#_3-nfs工作流程\",\"children\":[]},{\"level\":2,\"title\":\"2.1 服务器信息\",\"slug\":\"_2-1-服务器信息\",\"link\":\"#_2-1-服务器信息\",\"children\":[]},{\"level\":2,\"title\":\"2.2 防火墙配置\",\"slug\":\"_2-2-防火墙配置\",\"link\":\"#_2-2-防火墙配置\",\"children\":[]},{\"level\":2,\"title\":\"2.3 selinux沙盒\",\"slug\":\"_2-3-selinux沙盒\",\"link\":\"#_2-3-selinux沙盒\",\"children\":[]}],\"readingTime\":{\"minutes\":7.85,\"words\":2354},\"filePathRelative\":\"cloud/Linux/【Linux】部署NFS服务实现数据共享.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
