export const data = JSON.parse("{\"key\":\"v-161931c9\",\"path\":\"/cloud/Linux/%E3%80%90Linux%E3%80%91%E5%AE%89%E8%A3%85OpenJDK11%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B.html\",\"title\":\"有外网安装（在线安装）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/%E3%80%90Linux%E3%80%91%E5%AE%89%E8%A3%85OpenJDK11%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"有外网安装（在线安装）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"有外网安装（在线安装）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"下载离线包\",\"slug\":\"下载离线包\",\"link\":\"#下载离线包\",\"children\":[]},{\"level\":2,\"title\":\"下载完成之后上传服务器并解压\",\"slug\":\"下载完成之后上传服务器并解压\",\"link\":\"#下载完成之后上传服务器并解压\",\"children\":[]},{\"level\":2,\"title\":\"添加环境变量\",\"slug\":\"添加环境变量\",\"link\":\"#添加环境变量\",\"children\":[]},{\"level\":2,\"title\":\"验证jdk是否安装成功\",\"slug\":\"验证jdk是否安装成功\",\"link\":\"#验证jdk是否安装成功\",\"children\":[]}],\"readingTime\":{\"minutes\":1.09,\"words\":327},\"filePathRelative\":\"cloud/Linux/【Linux】安装OpenJDK11详细教程.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
