export const data = JSON.parse("{\"key\":\"v-69fccd2d\",\"path\":\"/cloud/Linux/%E3%80%90Linux%E3%80%91%E4%B8%AD%E4%B8%8D%E5%B0%8F%E5%BF%83%E8%AF%AF%E5%8D%B8%E8%BD%BD%E4%BA%86rpm%E5%91%BD%E4%BB%A4%E5%A6%82%E4%BD%95%E6%81%A2%E5%A4%8D%EF%BC%9F.html\",\"title\":\"问题复现\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\" 🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/%E3%80%90Linux%E3%80%91%E4%B8%AD%E4%B8%8D%E5%B0%8F%E5%BF%83%E8%AF%AF%E5%8D%B8%E8%BD%BD%E4%BA%86rpm%E5%91%BD%E4%BB%A4%E5%A6%82%E4%BD%95%E6%81%A2%E5%A4%8D%EF%BC%9F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"问题复现\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\" 🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"问题复现\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"补全 whereis rpm 缺少的文件\",\"slug\":\"补全-whereis-rpm-缺少的文件\",\"link\":\"#补全-whereis-rpm-缺少的文件\",\"children\":[]},{\"level\":2,\"title\":\"将rpmrc文件从没问题的环境（210）复制过来\",\"slug\":\"将rpmrc文件从没问题的环境-210-复制过来\",\"link\":\"#将rpmrc文件从没问题的环境-210-复制过来\",\"children\":[]},{\"level\":2,\"title\":\"出现这个问题：我们可以将没有问题的服务器中的 macros 文件复制过去\",\"slug\":\"出现这个问题-我们可以将没有问题的服务器中的-macros-文件复制过去\",\"link\":\"#出现这个问题-我们可以将没有问题的服务器中的-macros-文件复制过去\",\"children\":[]}],\"readingTime\":{\"minutes\":2.73,\"words\":818},\"filePathRelative\":\"cloud/Linux/【Linux】中不小心误卸载了rpm命令如何恢复？.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
