export const data = JSON.parse("{\"key\":\"v-728c3a8f\",\"path\":\"/about-the-author/\",\"title\":\"个人介绍 Q&A\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"portfolio\":true,\"title\":\"个人介绍 Q&A\",\"heroText\":\"关于作者\",\"bgImageDark\":\"/assets/image/2-dark.svg\",\"highlights\":[{\"header\":\"👨‍🎓个人贡献\",\"image\":\"/assets/image/blog.svg\",\"bgImage\":\"/assets/image/9-light.svg\",\"bgImageDark\":\"/assets/image/2-dark.svg\",\"highlights\":[{\"title\":\"🏅 2023年新星计划Linux运维方向导师\",\"link\":\"https://blog.csdn.net/liu_chen_yang?type=blog\"},{\"title\":\"🏅 华为云开发者社区专家博主\",\"link\":\"https://bbs.huaweicloud.com/community/usersnew/id_1661843828089234\"},{\"title\":\"🏅 阿里云开发者社区专家博主\",\"link\":\"https://developer.aliyun.com/profile/7yu26jk3lfqxg\"},{\"title\":\"🏅 CSDN博客专家\",\"link\":\"https://blog.csdn.net/liu_chen_yang?type=blog\"},{\"title\":\"🏅 CSDN内容合伙人\",\"link\":\"https://blog.csdn.net/liu_chen_yang?type=blog\"},{\"title\":\"🏅 CSDN-2022年度社区之星\",\"link\":\"https://bbs.csdn.net/forums/lcy?spm=1001.2014.3001.6682\"},{\"title\":\"🏅 运维领域优质创作者\",\"link\":\"https://blog.csdn.net/liu_chen_yang?type=blog\"},{\"title\":\"🏅 云计算领域优质创作者\",\"link\":\"https://blog.csdn.net/liu_chen_yang?type=blog\"},{\"title\":\"🏅 程序员Liucy的学习指南1\",\"link\":\"http://liuchenyang.top\"},{\"title\":\"🏅 程序员Liucy的学习指南2\",\"link\":\"https://liuchenyang0703.github.io/ToLiucyLinux/\"},{\"title\":\"🐋 运维交流社区\",\"link\":\"https://bbs.csdn.net/forums/lcy\"}]}],\"copyright\":false,\"footer\":\"使用 <a href=\\\"https://theme-hope.vuejs.press/zh/\\\" target=\\\"_blank\\\">VuePress Theme Hope</a> 主题 | MIT 协议, 版权所有 © 2023-present Liucy | <img src=\\\"https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202312142253822.png\\\" height=\\\"15\\\" width=\\\"15\\\"/> <a href=\\\"http://beian.miit.gov.cn/\\\" target=\\\"_blank\\\">京ICP备2023037493号-1</a>\",\"description\":\"公众号 如果大家想要实时关注我更新的文章以及分享的干货的话，可以关注我的公众号小刘Linux。 小刘Linux 公众号封面\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/about-the-author/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"个人介绍 Q&A\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"公众号 如果大家想要实时关注我更新的文章以及分享的干货的话，可以关注我的公众号小刘Linux。 小刘Linux 公众号封面\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"个人介绍 Q&A\\\",\\\"description\\\":\\\"公众号 如果大家想要实时关注我更新的文章以及分享的干货的话，可以关注我的公众号小刘Linux。 小刘Linux 公众号封面\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.01,\"words\":302},\"filePathRelative\":\"about-the-author/readme.md\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
