export const data = JSON.parse("{\"key\":\"v-d92b2ec6\",\"path\":\"/database/windows10_11%E5%AE%89%E8%A3%85%E6%B0%B8%E4%B9%85%E7%89%88%20Navicat%20Premium%2015%20%E6%95%B0%E6%8D%AE%E5%BA%93.html\",\"title\":\"windows10&11安装永久版 Navicat Premium 15 数据库\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"windows10&11安装永久版 Navicat Premium 15 数据库\",\"icon\":\"circle-info\",\"order\":11,\"tag\":[\"Windows\",\"mysql\",\"Navicat\",\"运维\"],\"category\":[\"Windows\",\"mysql\"],\"pageview\":false,\"date\":\"2024-03-24T00:00:00.000Z\",\"comment\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/database/windows10_11%E5%AE%89%E8%A3%85%E6%B0%B8%E4%B9%85%E7%89%88%20Navicat%20Premium%2015%20%E6%95%B0%E6%8D%AE%E5%BA%93.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"windows10&11安装永久版 Navicat Premium 15 数据库\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Windows\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"mysql\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Navicat\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-24T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"windows10&11安装永久版 Navicat Premium 15 数据库\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.82,\"words\":547},\"filePathRelative\":\"database/windows10&11安装永久版 Navicat Premium 15 数据库.md\",\"localizedDate\":\"2024年3月24日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
