<template><div><blockquote>
<p>🍁<strong>博主简介</strong></p>
<p>  🏅<a href="https://blog.csdn.net/liu_chen_yang?type=blog" target="_blank" rel="noopener noreferrer">云计算领域优质创作者</a><br>
  🏅<a href="https://bbs.huaweicloud.com/community/myblog" target="_blank" rel="noopener noreferrer">华为云开发者社区专家博主</a><br>
  🏅<a href="https://developer.aliyun.com/my?spm=a2c6h.13148508.setting.3.21fc4f0eCmz1v3#/article?_k=zooqoz" target="_blank" rel="noopener noreferrer">阿里云开发者社区专家博主</a><br>
💊<strong>交流社区：</strong><a href="https://bbs.csdn.net/forums/lcy" target="_blank" rel="noopener noreferrer">运维交流社区</a> 欢迎大家的加入！</p>
</blockquote>
<h2 id="报错详情" tabindex="-1"><a class="header-anchor" href="#报错详情"><span>报错详情</span></a></h2>
<blockquote>
<p>查看k8s中其他节点的cpu，memory的使用率情况</p>
</blockquote>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@k8s-master ~]# kubectl top nodes</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">error:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Metrics</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> API</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> not</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> available</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="解决方式" tabindex="-1"><a class="header-anchor" href="#解决方式"><span>解决方式</span></a></h2>
<h3 id="_1、下载-metrics-server-components-yaml" tabindex="-1"><a class="header-anchor" href="#_1、下载-metrics-server-components-yaml"><span>1、下载 metrics-server-components.yaml</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">wget</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -O</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-components.yaml</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161404720.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="_2、将-metrics-server-components-yaml中的-k8s-gcr-io-更改为阿里云镜像地址" tabindex="-1"><a class="header-anchor" href="#_2、将-metrics-server-components-yaml中的-k8s-gcr-io-更改为阿里云镜像地址"><span>2、将 metrics-server-components.yaml中的 <a href="http://k8s.gcr.io" target="_blank" rel="noopener noreferrer">k8s.gcr.io</a> 更改为阿里云镜像地址</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sed</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -i</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 's/registry.k8s.io\/metrics-server/registry.cn-hangzhou.aliyuncs.com\/google_containers/g'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-components.yaml</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>修改完可以看一下，有时候wget拉取的是最新的yaml而镜像源会变，就会修改不成功，导致拉取镜像失败。就比如昨天还是0.6.2今天就变成了0.6.3更新了一个新版本，而且镜像前缀也变了，就拉取不下来，找了半天才找到这个问题。</p>
<p>在140行，更换完之后应该是这样的：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">         image:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> registry.cn-hangzhou.aliyuncs.com/google_containers/metrics-server:v0.6.3</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_3、执行-metrics-server-components-yaml" tabindex="-1"><a class="header-anchor" href="#_3、执行-metrics-server-components-yaml"><span>3、执行 metrics-server-components.yaml</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apply</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -f</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-components.yaml</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_4、查看pod" tabindex="-1"><a class="header-anchor" href="#_4、查看pod"><span>4、查看pod</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pod</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> me</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161404782.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>发现是0/1，表示未启动。</p>
<p>有可能是镜像没有拉到，可直接下载镜像进行导入：<a href="https://download.csdn.net/download/liu_chen_yang/87602850" target="_blank" rel="noopener noreferrer">K8S部署metrics-server-0.6.2镜像文件及yaml文件<br>
</a><br>
也有一种报错如下：</p>
<h4 id="_4-1-查看-metrics-server-647596b58-fgwzg-日志" tabindex="-1"><a class="header-anchor" href="#_4-1-查看-metrics-server-647596b58-fgwzg-日志"><span>4.1 查看 metrics-server-647596b58-fgwzg 日志</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logs</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -n</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> kube-system</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-647596b58-fgwzg</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logs</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -f</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -n</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> kube-system</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-647596b58-fgwzg</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>-n 查看最后几行</li>
<li>-f 持续查看</li>
</ul>
<h4 id="_4-2-发现报错-x509-cannot-validate-certificate-for-172-16-11-223-because-it-doesn-t-contain-any-ip-sans-node-k8s-node2" tabindex="-1"><a class="header-anchor" href="#_4-2-发现报错-x509-cannot-validate-certificate-for-172-16-11-223-because-it-doesn-t-contain-any-ip-sans-node-k8s-node2"><span>4.2 发现报错： x509: cannot validate certificate for 172.16.11.223 because it doesn't contain any IP SANs&quot; node=&quot;k8s-node2&quot;</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">E0320</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 02:11:51.486654</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> scraper.go:140]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "Failed to scrape node"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> err="Get </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">https://172.16.11.221:10250/metrics/resource</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">: x509: cannot validate certificate for 172.16.11.221 because it doesn't contain any IP SANs"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> node="k8s-master"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">I0320</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 02:12:00.517727</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server.go:187]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "Failed probe"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> probe="metric-storage-ready"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> err="no metrics to serve"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">E0320</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 02:12:06.476898</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> scraper.go:140]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "Failed to scrape node"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> err="Get </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">https://172.16.11.222:10250/metrics/resource</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">: x509: cannot validate certificate for 172.16.11.222 because it doesn't contain any IP SANs"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> node="k8s-node1"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">E0320</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 02:12:06.486505</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">       1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> scraper.go:140]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "Failed to scrape node"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> err="Get </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">https://172.16.11.223:10250/metrics/resource</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">: x509: cannot validate certificate for 172.16.11.223 because it doesn't contain any IP SANs"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> node="k8s-node2"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-3-需要修改-metrics-server-components-yaml-配置忽略ca验证" tabindex="-1"><a class="header-anchor" href="#_4-3-需要修改-metrics-server-components-yaml-配置忽略ca验证"><span>4.3 需要修改 metrics-server-components.yaml 配置忽略CA验证</span></a></h4>
<p>大概在140行。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-components.yaml</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> spec:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">      containers:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">      -</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> args:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --cert-dir=/tmp</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --secure-port=4443</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --kubelet-use-node-status-port</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --metric-resolution=15s</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --kubelet-insecure-tls</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">                   ###新增--kubelet-insecure-tls 就不会去验证Kubelets提供的服务证书的CA</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-4-修改完之后重新应用-metrics-server-components-yaml" tabindex="-1"><a class="header-anchor" href="#_4-4-修改完之后重新应用-metrics-server-components-yaml"><span>4.4 修改完之后重新应用 metrics-server-components.yaml</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apply</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -f</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> metrics-server-components.yaml</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161404774.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="_4-5-再次查看pod启动状态" tabindex="-1"><a class="header-anchor" href="#_4-5-再次查看pod启动状态"><span>4.5 再次查看pod启动状态</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pod</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -A</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> |</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> me</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>发现是1/1，启动成功。</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161404774.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="_5、验证是否成功" tabindex="-1"><a class="header-anchor" href="#_5、验证是否成功"><span>5、验证是否成功</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">kubectl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> top</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> nodes</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161404980.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>完成。</p>
</div></template>


