import comp from "D:/JAVA项目/new_cs/rc67/src/.vuepress/.temp/pages/document/Docker/【Docker】查看每层镜像的大小.html.vue"
const data = JSON.parse("{\"path\":\"/document/Docker/%E3%80%90Docker%E3%80%91%E6%9F%A5%E7%9C%8B%E6%AF%8F%E5%B1%82%E9%95%9C%E5%83%8F%E7%9A%84%E5%A4%A7%E5%B0%8F.html\",\"title\":\"【Docker】查看每层镜像的大小\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Docker】查看每层镜像的大小\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\",\"Docker\"],\"tag\":[\"Linux\",\"Docker\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-16T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"gitInclude\":[],\"description\":\"👨‍🎓博主简介 🏅云计算领域优质创作者 🏅华为云开发者社区专家博主 🏅阿里云开发者社区专家博主 💊交流社区：运维交流社区 欢迎大家的加入！ 🐋 希望大家多多支持，我们一起进步！😄 🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗 docker history image 使用：docker hist...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/document/Docker/%E3%80%90Docker%E3%80%91%E6%9F%A5%E7%9C%8B%E6%AF%8F%E5%B1%82%E9%95%9C%E5%83%8F%E7%9A%84%E5%A4%A7%E5%B0%8F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Docker】查看每层镜像的大小\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 🏅云计算领域优质创作者 🏅华为云开发者社区专家博主 🏅阿里云开发者社区专家博主 💊交流社区：运维交流社区 欢迎大家的加入！ 🐋 希望大家多多支持，我们一起进步！😄 🎉如果文章对你有帮助的话，欢迎 点赞 👍🏻 评论 💬 收藏 ⭐️ 加关注+💗 docker history image 使用：docker hist...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Docker\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-16T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Docker】查看每层镜像的大小\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"docker history image\",\"slug\":\"docker-history-image\",\"link\":\"#docker-history-image\",\"children\":[]}],\"readingTime\":{\"minutes\":1.58,\"words\":474},\"filePathRelative\":\"document/Docker/【Docker】查看每层镜像的大小.md\",\"localizedDate\":\"2024年12月16日\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
