export const data = JSON.parse("{\"key\":\"v-b7cc7196\",\"path\":\"/cloud/Linux/Linux%E4%B8%ADgcc4.8.5%E5%8D%87%E7%BA%A7%E5%88%B0gcc5.4.0%E7%94%A8%E5%B7%B2%E7%BB%8F%E7%BC%96%E8%AF%91%E5%A5%BD%E7%9A%84%E5%AE%89%E8%A3%85%E5%8C%85%E5%8D%87%E7%BA%A7%EF%BC%88%E9%87%8D%E7%82%B9%E6%98%AF%E4%B8%8D%E7%94%A8%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%9B%B4%E7%9C%81%E6%97%B6%EF%BC%89.html\",\"title\":\"前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"[toc] &emsp;&emsp;如有遇到没有网络的情况下可以选择用这种方法来做，前提是要先下载好这个包。 还有一个是可以在有网的情况下做的，就是编译安装； 链接地址：👉Centos7 gcc4.8.5升级到版本gcc5.4.0 (https://blog.csdn.net/liuchenyang/article/details/123711779...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/Linux%E4%B8%ADgcc4.8.5%E5%8D%87%E7%BA%A7%E5%88%B0gcc5.4.0%E7%94%A8%E5%B7%B2%E7%BB%8F%E7%BC%96%E8%AF%91%E5%A5%BD%E7%9A%84%E5%AE%89%E8%A3%85%E5%8C%85%E5%8D%87%E7%BA%A7%EF%BC%88%E9%87%8D%E7%82%B9%E6%98%AF%E4%B8%8D%E7%94%A8%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%9B%B4%E7%9C%81%E6%97%B6%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[toc] &emsp;&emsp;如有遇到没有网络的情况下可以选择用这种方法来做，前提是要先下载好这个包。 还有一个是可以在有网的情况下做的，就是编译安装； 链接地址：👉Centos7 gcc4.8.5升级到版本gcc5.4.0 (https://blog.csdn.net/liuchenyang/article/details/123711779...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"下载安装包\",\"slug\":\"下载安装包\",\"link\":\"#下载安装包\",\"children\":[]},{\"level\":2,\"title\":\"解压安装包\",\"slug\":\"解压安装包\",\"link\":\"#解压安装包\",\"children\":[]},{\"level\":2,\"title\":\"软连接gcc库\",\"slug\":\"软连接gcc库\",\"link\":\"#软连接gcc库\",\"children\":[]},{\"level\":2,\"title\":\"软连接gcc版本\",\"slug\":\"软连接gcc版本\",\"link\":\"#软连接gcc版本\",\"children\":[]}],\"readingTime\":{\"minutes\":1.73,\"words\":520},\"filePathRelative\":\"cloud/Linux/Linux中gcc4.8.5升级到gcc5.4.0用已经编译好的安装包升级（重点是不用编译安装，可以更省时）.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
