export const data = JSON.parse("{\"key\":\"v-e6b64d9c\",\"path\":\"/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%90%AD%E5%BB%BA%20postfix_dovecot_mysql%20%EF%BC%88%E7%BB%88%E6%9E%81%E7%89%88%20%E8%B6%85%E8%AF%A6%E7%BB%86%20%E4%BA%B2%E6%B5%8B%E5%A4%9A%E9%81%8D%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%89.html\",\"title\":\"前言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/cloud/Linux/%E3%80%90Linux%E3%80%91%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%90%AD%E5%BB%BA%20postfix_dovecot_mysql%20%EF%BC%88%E7%BB%88%E6%9E%81%E7%89%88%20%E8%B6%85%E8%AF%A6%E7%BB%86%20%E4%BA%B2%E6%B5%8B%E5%A4%9A%E9%81%8D%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍁博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区专家博...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1、部署数据库（mariadb）\",\"slug\":\"_1、部署数据库-mariadb\",\"link\":\"#_1、部署数据库-mariadb\",\"children\":[]},{\"level\":2,\"title\":\"2、库、表结构导入\",\"slug\":\"_2、库、表结构导入\",\"link\":\"#_2、库、表结构导入\",\"children\":[]}],\"readingTime\":{\"minutes\":18.76,\"words\":5628},\"filePathRelative\":\"cloud/Linux/【Linux】邮件服务器搭建 postfix+dovecot+mysql （终极版 超详细 亲测多遍无问题）.md\",\"copyright\":{\"author\":\"LiucyLinux(LiucyLinux.cn)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
