<template><div><h2 id="前提" tabindex="-1"><a class="header-anchor" href="#前提" aria-hidden="true">#</a> 前提</h2>
<p><strong>必须要有docker</strong>，如果没有可以去查看：<a href="https://blog.csdn.net/liu_chen_yang/article/details/123842609" target="_blank" rel="noopener noreferrer">linux（centos）中部署docker（步骤超全，含带一些发展史和一些概念）<ExternalLinkIcon/></a>，有安装步骤。</p>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161445579.gif" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="两种安装-部署方式" tabindex="-1"><a class="header-anchor" href="#两种安装-部署方式" aria-hidden="true">#</a> 两种安装/部署方式</h2>
<figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161445873.gif" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="第一种-按照官方文档下载docker-compose包来安装" tabindex="-1"><a class="header-anchor" href="#第一种-按照官方文档下载docker-compose包来安装" aria-hidden="true">#</a> 第一种：按照官方文档下载docker-compose包来安装</h3>
<h4 id="_1-下载docker-compose" tabindex="-1"><a class="header-anchor" href="#_1-下载docker-compose" aria-hidden="true">#</a> （1）下载docker-compose</h4>
<p>执行如下命令进行下载</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">curl</span> <span class="token parameter variable">-L</span> <span class="token string">"https://github.com/docker/compose/releases/download/1.29.2/docker-compose-<span class="token variable"><span class="token variable">$(</span><span class="token function">uname</span> <span class="token parameter variable">-s</span><span class="token variable">)</span></span>-<span class="token variable"><span class="token variable">$(</span><span class="token function">uname</span> <span class="token parameter variable">-m</span><span class="token variable">)</span></span>"</span> <span class="token parameter variable">-o</span> /usr/local/bin/docker-compose
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>若速度较慢，可以使用如下命令：</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">curl</span> <span class="token parameter variable">-L</span> <span class="token string">"https://mirror.ghproxy.com/https://github.com/docker/compose/releases/download/1.29.2/docker-compose-<span class="token variable"><span class="token variable">$(</span><span class="token function">uname</span> <span class="token parameter variable">-s</span><span class="token variable">)</span></span>-<span class="token variable"><span class="token variable">$(</span><span class="token function">uname</span> <span class="token parameter variable">-m</span><span class="token variable">)</span></span>"</span> <span class="token parameter variable">-o</span> /usr/local/bin/docker-compose
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><blockquote>
<p>同时这种部署方式也可作为离线部署方式：只需要将包下载下来，放到服务器中指定位置即可；<br>
下载地址：<a href="https://download.csdn.net/download/liu_chen_yang/89428645" target="_blank" rel="noopener noreferrer">docker-compose1.29.2离线包<ExternalLinkIcon/></a></p>
</blockquote>
<h4 id="_2-修改目录权限" tabindex="-1"><a class="header-anchor" href="#_2-修改目录权限" aria-hidden="true">#</a> （2）修改目录权限</h4>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">chmod</span>  +x /usr/local/bin/docker-compose
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="_3-创建软连接" tabindex="-1"><a class="header-anchor" href="#_3-创建软连接" aria-hidden="true">#</a> （3）创建软连接</h4>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">ln</span> <span class="token parameter variable">-s</span> /usr/local/bin/docker-compose /usr/bin/docker-compose
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="_4-验证安装是否完成" tabindex="-1"><a class="header-anchor" href="#_4-验证安装是否完成" aria-hidden="true">#</a> （4）验证安装是否完成</h4>
<p>执行如下命令，如果可以正常显示版本号，则表示已经完成</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">docker-compose</span> <span class="token parameter variable">--version</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="https://lcy-blog.oss-cn-beijing.aliyuncs.com/blog/202412161445141.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="第二种-使用pip-install-的方式安装" tabindex="-1"><a class="header-anchor" href="#第二种-使用pip-install-的方式安装" aria-hidden="true">#</a> 第二种：使用pip install 的方式安装</h3>
<p>因为docker-compose是使用python开发的，因此可以通过pip install 的方式安装</p>
<h4 id="_1-首先需要确保pip已经安装完成-如下" tabindex="-1"><a class="header-anchor" href="#_1-首先需要确保pip已经安装完成-如下" aria-hidden="true">#</a> （1）首先需要确保pip已经安装完成，如下</h4>
<p>如下，表示pip为基于python3.9的版本，这里最好安装基于python3.6以上的pip</p>
<p>这里有安装文档：<a href="https://blog.csdn.net/liu_chen_yang/article/details/123680594" target="_blank" rel="noopener noreferrer">Linux下安装Python3.6.8（超级详细）<ExternalLinkIcon/></a>，可以采纳。</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~<span class="token punctuation">]</span><span class="token comment"># pip3 --version</span>
pip <span class="token number">21.2</span>.4 from /usr/local/python3/lib/python3.9/site-packages/pip <span class="token punctuation">(</span>python <span class="token number">3.9</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_2-升级pip的版本" tabindex="-1"><a class="header-anchor" href="#_2-升级pip的版本" aria-hidden="true">#</a> （2）升级pip的版本</h4>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>python3 <span class="token parameter variable">-m</span> pip <span class="token function">install</span> <span class="token parameter variable">--upgrade</span> pip
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如：</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~<span class="token punctuation">]</span><span class="token comment"># python3 -m pip install --upgrade pip</span>
Looking <span class="token keyword">in</span> indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: pip <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span><span class="token number">21.2</span>.4<span class="token punctuation">)</span>
Collecting pip
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl <span class="token punctuation">(</span><span class="token number">1.7</span> MB<span class="token punctuation">)</span>
     <span class="token operator">|</span>████████████████████████████████<span class="token operator">|</span> <span class="token number">1.7</span> MB <span class="token number">105</span> kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip <span class="token number">21.2</span>.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
  WARNING: The scripts pip, pip3 and pip3.9 are installed <span class="token keyword">in</span> <span class="token string">'/usr/local/python3/bin'</span> <span class="token function">which</span> is not on <span class="token environment constant">PATH</span><span class="token builtin class-name">.</span>
  Consider adding this directory to <span class="token environment constant">PATH</span> or, <span class="token keyword">if</span> you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.3.1
WARNING: Running pip as the <span class="token string">'root'</span> user can result <span class="token keyword">in</span> broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_3-安装docker-compose" tabindex="-1"><a class="header-anchor" href="#_3-安装docker-compose" aria-hidden="true">#</a> （3）安装docker-compose</h4>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>pip3 <span class="token function">install</span> <span class="token function">docker-compose</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如下：</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~<span class="token punctuation">]</span><span class="token comment"># pip3 install docker-compose</span>
Looking <span class="token keyword">in</span> indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: <span class="token function">docker-compose</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span><span class="token number">1.29</span>.2<span class="token punctuation">)</span>
Requirement already satisfied: docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">5.0</span>.3<span class="token punctuation">)</span>
Requirement already satisfied: PyYAML<span class="token operator">&lt;</span><span class="token number">6</span>,<span class="token operator">>=</span><span class="token number">3.10</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">5.4</span>.1<span class="token punctuation">)</span>
Requirement already satisfied: jsonschema<span class="token operator">&lt;</span><span class="token number">4</span>,<span class="token operator">>=</span><span class="token number">2.5</span>.1 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">3.2</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: python-dotenv<span class="token operator">&lt;</span><span class="token number">1</span>,<span class="token operator">>=</span><span class="token number">0.13</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">0.19</span>.1<span class="token punctuation">)</span>
Requirement already satisfied: texttable<span class="token operator">&lt;</span><span class="token number">2</span>,<span class="token operator">>=</span><span class="token number">0.9</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.6</span>.4<span class="token punctuation">)</span>
Requirement already satisfied: websocket-client<span class="token operator">&lt;</span><span class="token number">1</span>,<span class="token operator">>=</span><span class="token number">0.32</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">0.59</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: distro<span class="token operator">&lt;</span><span class="token number">2</span>,<span class="token operator">>=</span><span class="token number">1.5</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.6</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: docopt<span class="token operator">&lt;</span><span class="token number">1</span>,<span class="token operator">>=</span><span class="token number">0.6</span>.1 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">0.6</span>.2<span class="token punctuation">)</span>
Requirement already satisfied: dockerpty<span class="token operator">&lt;</span><span class="token number">1</span>,<span class="token operator">>=</span><span class="token number">0.4</span>.1 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">0.4</span>.1<span class="token punctuation">)</span>
Requirement already satisfied: requests<span class="token operator">&lt;</span><span class="token number">3</span>,<span class="token operator">>=</span><span class="token number">2.20</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from <span class="token function">docker-compose</span><span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">2.26</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">2.8</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: six<span class="token operator">>=</span><span class="token number">1.3</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from dockerpty<span class="token operator">&lt;</span><span class="token number">1</span>,<span class="token operator">>=</span><span class="token number">0.4</span>.1-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.16</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: attrs<span class="token operator">>=</span><span class="token number">17.4</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from jsonschema<span class="token operator">&lt;</span><span class="token number">4</span>,<span class="token operator">>=</span><span class="token number">2.5</span>.1-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">21.2</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: pyrsistent<span class="token operator">>=</span><span class="token number">0.14</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from jsonschema<span class="token operator">&lt;</span><span class="token number">4</span>,<span class="token operator">>=</span><span class="token number">2.5</span>.1-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">0.18</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: setuptools <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from jsonschema<span class="token operator">&lt;</span><span class="token number">4</span>,<span class="token operator">>=</span><span class="token number">2.5</span>.1-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">57.4</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: urllib<span class="token operator"><span class="token file-descriptor important">3</span>&lt;</span><span class="token number">1.27</span>,<span class="token operator">>=</span><span class="token number">1.21</span>.1 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from requests<span class="token operator">&lt;</span><span class="token number">3</span>,<span class="token operator">>=</span><span class="token number">2.20</span>.0-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.26</span>.6<span class="token punctuation">)</span>
Requirement already satisfied: charset-normalizer~<span class="token operator">=</span><span class="token number">2.0</span>.0 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from requests<span class="token operator">&lt;</span><span class="token number">3</span>,<span class="token operator">>=</span><span class="token number">2.20</span>.0-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">2.0</span>.7<span class="token punctuation">)</span>
Requirement already satisfied: idna<span class="token operator">&lt;</span><span class="token number">4</span>,<span class="token operator">>=</span><span class="token number">2.5</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from requests<span class="token operator">&lt;</span><span class="token number">3</span>,<span class="token operator">>=</span><span class="token number">2.20</span>.0-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">3.3</span><span class="token punctuation">)</span>
Requirement already satisfied: certifi<span class="token operator">>=</span><span class="token number">2017.4</span>.17 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from requests<span class="token operator">&lt;</span><span class="token number">3</span>,<span class="token operator">>=</span><span class="token number">2.20</span>.0-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">2021.5</span>.30<span class="token punctuation">)</span>
Requirement already satisfied: cryptography<span class="token operator">>=</span><span class="token number">2.5</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2-<span class="token operator">></span>docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">35.0</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: pynacl<span class="token operator">>=</span><span class="token number">1.0</span>.1 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2-<span class="token operator">></span>docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.4</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: bcrypt<span class="token operator">>=</span><span class="token number">3.1</span>.3 <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2-<span class="token operator">></span>docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">3.2</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: cffi<span class="token operator">>=</span><span class="token number">1.1</span> <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from bcrypt<span class="token operator">>=</span><span class="token number">3.1</span>.3-<span class="token operator">></span>paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2-<span class="token operator">></span>docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">1.15</span>.0<span class="token punctuation">)</span>
Requirement already satisfied: pycparser <span class="token keyword">in</span> /usr/local/python3/lib/python3.9/site-packages <span class="token punctuation">(</span>from cffi<span class="token operator">>=</span><span class="token number">1.1</span>-<span class="token operator">></span>bcrypt<span class="token operator">>=</span><span class="token number">3.1</span>.3-<span class="token operator">></span>paramiko<span class="token operator">>=</span><span class="token number">2.4</span>.2-<span class="token operator">></span>docker<span class="token punctuation">[</span>ssh<span class="token punctuation">]</span><span class="token operator">>=</span><span class="token number">5</span>-<span class="token operator">></span>docker-compose<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token number">2.20</span><span class="token punctuation">)</span>
WARNING: Running pip as the <span class="token string">'root'</span> user can result <span class="token keyword">in</span> broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-验证是否安装完成" tabindex="-1"><a class="header-anchor" href="#_4-验证是否安装完成" aria-hidden="true">#</a> （4）验证是否安装完成</h4>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">docker-compose</span> <span class="token parameter variable">-version</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如下</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~<span class="token punctuation">]</span><span class="token comment"># docker-compose -version</span>
<span class="token function">docker-compose</span> version <span class="token number">1.29</span>.2, build unknown
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h2>
<p><strong>相关文章：</strong></p>
<blockquote>
<p>①、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124665726?spm=1001.2014.3001.5502" target="_blank" rel="noopener noreferrer">Docker——denied: requested access to the resource is denied问题以及解决方法<ExternalLinkIcon/></a><br>
②、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124705622" target="_blank" rel="noopener noreferrer">Docker搭建harbor私有镜像仓库（命令行模式）<ExternalLinkIcon/></a><br>
③、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124623482" target="_blank" rel="noopener noreferrer">Linux中基于Docker搭建harbor私有镜像仓库（超级详细）<ExternalLinkIcon/></a>🔥🔥<br>
④、<a href="https://blog.csdn.net/liu_chen_yang/article/details/124670946?spm=1001.2014.3001.5502" target="_blank" rel="noopener noreferrer">Docker发布/上传镜像到dockerhub&amp;&amp;下载/拉取镜像&amp;&amp;删除dockerhub镜像<ExternalLinkIcon/></a><br>
⑤、<a href="https://liucy.blog.csdn.net/article/details/129082503" target="_blank" rel="noopener noreferrer">【Docker】之docker-compose的介绍与命令的使用<ExternalLinkIcon/></a></p>
</blockquote>
</div></template>


