export const data = JSON.parse("{\"key\":\"v-f11cf324\",\"path\":\"/Docker/%E3%80%90Docker%E3%80%91%E5%A6%82%E4%BD%95%E5%B0%86%E5%B7%B2%E6%9C%89%E7%9A%84%E5%AE%B9%E5%99%A8%E6%89%93%E4%B8%BA%E9%95%9C%E5%83%8F%EF%BC%9F%EF%BC%9F%EF%BC%9F.html\",\"title\":\"【Docker】如何将已有的容器打为镜像？？？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"【Docker】如何将已有的容器打为镜像？？？\",\"icon\":\"circle-info\",\"order\":1,\"category\":[\"Linux\",\"Docker\"],\"tag\":[\"Linux\",\"Docker\",\"运维\"],\"pageview\":false,\"date\":\"2024-12-16T00:00:00.000Z\",\"comment\":false,\"breadcrumb\":false,\"description\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liuchenyang.top/ToLiucyLinux/Docker/%E3%80%90Docker%E3%80%91%E5%A6%82%E4%BD%95%E5%B0%86%E5%B7%B2%E6%9C%89%E7%9A%84%E5%AE%B9%E5%99%A8%E6%89%93%E4%B8%BA%E9%95%9C%E5%83%8F%EF%BC%9F%EF%BC%9F%EF%BC%9F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"ToLiucyLinux\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"【Docker】如何将已有的容器打为镜像？？？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"👨‍🎓博主简介 &emsp;&emsp;🏅云计算领域优质创作者 (https://blog.csdn.net/liuchenyang?type=blog) &emsp;&emsp;🏅华为云开发者社区专家博主 (https://bbs.huaweicloud.com/community/myblog) &emsp;&emsp;🏅阿里云开发者社区...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Liucy\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Linux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Docker\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"运维\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-12-16T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"【Docker】如何将已有的容器打为镜像？？？\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-12-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Liucy\\\",\\\"url\\\":\\\"http://liuchenyang.top\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.94,\"words\":282},\"filePathRelative\":\"Docker/【Docker】如何将已有的容器打为镜像？？？.md\",\"localizedDate\":\"2024年12月16日\",\"copyright\":{\"author\":\"LiucyLinux(http://liuchenyang.top)\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
